import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  {
    id: 1,
    type: "qcm",
    question: "Qu est-ce qu un demon (daemon) sous Linux ?",
    options: [
      "Un programme avec interface graphique",
      "Un programme qui tourne en arriere-plan sans interaction utilisateur",
      "Un virus systeme",
      "Un fichier de configuration",
    ],
    correct: 1,
    explanation: "Un demon est un programme qui tourne en arriere-plan de maniere permanente. Il offre un service 24h/24 sans interface graphique.",
  },
  {
    id: 2,
    type: "qcm",
    question: "Par quelle lettre se terminent generalement les noms de demons Linux ?",
    options: ["s", "x", "d", "r"],
    correct: 2,
    explanation: "Les demons se terminent par d : sshd, httpd, named, dhcpd. Ce d signifie daemon.",
  },
  {
    id: 3,
    type: "qcm",
    question: "Quel est le gestionnaire de services sur les distributions Linux modernes ?",
    options: ["init", "upstart", "systemd", "launchd"],
    correct: 2,
    explanation: "systemd est le systeme d initialisation et de gestion des services sur Ubuntu, Fedora, Debian et Red Hat modernes.",
  },
  {
    id: 4,
    type: "qcm",
    question: "Quelle commande demarre un service avec systemd ?",
    options: [
      "service nomservice start",
      "systemctl start nomservice",
      "systemctl run nomservice",
      "start nomservice",
    ],
    correct: 1,
    explanation: "systemctl start nomservice demarre un service. Sur Fedora, l ancienne syntaxe service nomservice start est aussi valide.",
  },
  {
    id: 5,
    type: "qcm",
    question: "Quelle commande active un service au demarrage du systeme ?",
    options: [
      "systemctl start nomservice",
      "systemctl activate nomservice",
      "systemctl enable nomservice",
      "systemctl boot nomservice",
    ],
    correct: 2,
    explanation: "systemctl enable configure le service pour demarrer automatiquement a chaque boot. systemctl start le demarre uniquement pour la session en cours.",
  },
  {
    id: 6,
    type: "qcm",
    question: "Quelle commande affiche les logs d un service en temps reel ?",
    options: [
      "journalctl -u sshd",
      "journalctl -f -u sshd",
      "tail /var/log/sshd",
      "logs -f sshd",
    ],
    correct: 1,
    explanation: "journalctl -f -u sshd suit les logs en temps reel (-f = follow). Sans -f, journalctl -u sshd affiche les logs existants.",
  },
  {
    id: 7,
    type: "qcm",
    question: "Quelle commande permet de changer le hostname de maniere permanente ?",
    options: [
      "hostname srv1",
      "hostnamectl set-hostname srv1.ofppt.local",
      "nano /etc/hostname",
      "nmcli hostname srv1",
    ],
    correct: 1,
    explanation: "hostnamectl set-hostname modifie /etc/hostname de maniere permanente. La commande hostname seule est temporaire.",
  },
  {
    id: 8,
    type: "qcm",
    question: "Quelle commande nmcli configure une IP statique ?",
    options: [
      "nmcli connection set ens3 ipv4.addresses 192.168.1.10/24",
      "nmcli connection modify ens3 ipv4.addresses 192.168.1.10/24",
      "nmcli interface modify ens3 ip 192.168.1.10",
      "nmcli ip set ens3 192.168.1.10/24",
    ],
    correct: 1,
    explanation: "La syntaxe correcte est nmcli connection modify suivi du nom de l interface et du parametre a modifier.",
  },
  {
    id: 9,
    type: "qcm",
    question: "Quelle permission est requise pour un fichier Netplan ?",
    options: ["chmod 644", "chmod 777", "chmod 755", "chmod 600"],
    correct: 3,
    explanation: "chmod 600 donne lecture/ecriture au proprietaire uniquement. Netplan refuse d appliquer un fichier avec des permissions trop ouvertes.",
  },
  {
    id: 10,
    type: "qcm",
    question: "Quelle commande applique la configuration Netplan ?",
    options: ["netplan start", "netplan reload", "netplan apply", "systemctl restart netplan"],
    correct: 2,
    explanation: "netplan apply lit le fichier YAML et applique la configuration reseau.",
  },
  {
    id: 11,
    type: "qcm",
    question: "Quelle commande cree un utilisateur sur Ubuntu avec son repertoire home automatiquement ?",
    options: ["useradd user1", "adduser user1", "createuser user1", "newuser user1"],
    correct: 1,
    explanation: "adduser (Ubuntu) cree le repertoire home automatiquement et demande le mot de passe. useradd est plus manuel et necessite passwd user1 en plus.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Quelle commande ajoute un utilisateur au groupe sudo sans retirer ses autres groupes ?",
    options: [
      "usermod -G sudo user1",
      "usermod -aG sudo user1",
      "groupadd sudo user1",
      "addgroup user1 sudo",
    ],
    correct: 1,
    explanation: "usermod -aG : -a = append (ne retire pas des autres groupes), -G = groupe supplementaire. Sans -a, l utilisateur est retire de tous ses autres groupes.",
  },
  {
    id: 13,
    type: "qcm",
    question: "Quelle commande supprime un utilisateur ET son repertoire home ?",
    options: [
      "userdel user1",
      "deluser user1",
      "userdel -r user1",
      "rmuser user1",
    ],
    correct: 2,
    explanation: "userdel -r supprime l utilisateur et son repertoire home. Sans -r, le repertoire home est conserve.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Quel fichier contient les mots de passe chiffres des utilisateurs ?",
    options: ["/etc/passwd", "/etc/shadow", "/etc/group", "/etc/users"],
    correct: 1,
    explanation: "/etc/shadow contient les mots de passe chiffres et les politiques de mots de passe. /etc/passwd contient les informations des utilisateurs mais pas les mots de passe.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Quelle commande force un utilisateur a changer son mot de passe a la prochaine connexion ?",
    options: ["passwd -l user1", "passwd -u user1", "passwd -e user1", "passwd -d user1"],
    correct: 2,
    explanation: "passwd -e (expire) force l utilisateur a changer son mot de passe a la prochaine connexion. -l verrouille le compte, -u le deverrouille.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Quelle commande affiche l UID, le GID et les groupes d un utilisateur ?",
    options: ["whoami", "groups user1", "id user1", "cat /etc/passwd | grep user1"],
    correct: 2,
    explanation: "id user1 affiche l UID, le GID principal et tous les groupes supplementaires de l utilisateur.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Quelle commande retire un utilisateur d un groupe ?",
    options: [
      "usermod -rG admins user1",
      "groupdel user1 admins",
      "gpasswd -d user1 admins",
      "userdel -g admins user1",
    ],
    correct: 2,
    explanation: "gpasswd -d user1 admins retire user1 du groupe admins.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Quelle commande installe le serveur SSH sur Ubuntu ?",
    options: [
      "sudo apt install ssh -y",
      "sudo apt install openssh-server -y",
      "sudo apt install sshd -y",
      "sudo apt install openssh -y",
    ],
    correct: 1,
    explanation: "Le package s appelle openssh-server sur Ubuntu et sur Fedora.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Quelle commande genere une cle RSA pour l authentification SSH ?",
    options: [
      "ssh-copy-id -t rsa -b 4096",
      "ssh-keygen -t rsa -b 4096",
      "openssl genrsa 4096",
      "ssh-keygen -r rsa",
    ],
    correct: 1,
    explanation: "ssh-keygen -t rsa -b 4096 genere une paire de cles RSA 4096 bits. La cle privee reste sur le client, la cle publique est copiee sur le serveur.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Quelle commande copie la cle publique SSH vers un serveur distant ?",
    options: [
      "scp ~/.ssh/id_rsa.pub user@server:",
      "ssh-copy-id user@server",
      "ssh-keygen --send user@server",
      "rsync ~/.ssh/id_rsa.pub user@server",
    ],
    correct: 1,
    explanation: "ssh-copy-id user@server copie automatiquement la cle publique dans ~/.ssh/authorized_keys du serveur distant.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Quelle commande netstat affiche les applications qui ouvrent un port ?",
    options: ["netstat -an", "netstat -i", "netstat -nr", "netstat -anp"],
    correct: 3,
    explanation: "netstat -anp affiche les sockets actifs avec les processus (PID et nom) associes a chaque port ouvert.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Quelle commande rpm verifie l existence d un package ?",
    options: ["rpm -qa dhcp", "rpm -check dhcp", "rpm -q dhcp", "rpm -verify dhcp"],
    correct: 2,
    explanation: "rpm -q nompackage verifie si un package est installe. S il est present, il affiche la version.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Quel groupe sous Fedora est l equivalent du groupe sudo d Ubuntu ?",
    options: ["admin", "root", "sudoers", "wheel"],
    correct: 3,
    explanation: "Le groupe wheel sur Fedora/Red Hat donne les privileges sudo. Sur Ubuntu c est le groupe sudo.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Que contient le fichier /etc/passwd ?",
    options: [
      "Les mots de passe chiffres",
      "La liste des groupes",
      "Les informations des utilisateurs : nom, UID, GID, home, shell",
      "Les cles SSH des utilisateurs",
    ],
    correct: 2,
    explanation: "/etc/passwd contient : nom:x:UID:GID:commentaire:home:shell. Le x signifie que le mot de passe est dans /etc/shadow.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Quelle commande installe un package sur Ubuntu avec confirmation automatique ?",
    options: [
      "sudo apt install nompackage",
      "sudo apt install nompackage -y",
      "sudo apt-get add nompackage -y",
      "sudo apt add nompackage -y",
    ],
    correct: 1,
    explanation: "L option -y repond automatiquement oui a toutes les confirmations.",
  },
  {
    id: 26,
    type: "qcm",
    question: "Quelle commande affiche toutes les adresses IP configurees sur le systeme ?",
    options: ["ifconfig -a", "ip a", "ip addr show", "A, B et C sont correctes"],
    correct: 3,
    explanation: "ifconfig -a, ip a et ip addr show affichent toutes les interfaces. ip a est la commande moderne recommandee.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Quelle commande affiche la table de routage ?",
    options: ["ifconfig -r", "netstat -i", "ip neigh", "route -n"],
    correct: 3,
    explanation: "route -n affiche la table de routage avec les adresses en numerique. ip route est l equivalent moderne.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Quel gestionnaire de packages utilise Ubuntu ?",
    options: ["rpm", "dnf", "yum", "apt"],
    correct: 3,
    explanation: "Ubuntu utilise apt (Advanced Package Tool). Fedora/Red Hat utilise dnf ou rpm.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Quelle directive dans sshd_config interdit la connexion SSH directe en root ?",
    options: ["RootLogin no", "PermitRoot no", "PermitRootLogin no", "DenyRoot yes"],
    correct: 2,
    explanation: "PermitRootLogin no empeche toute connexion SSH directe avec le compte root.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Quelle commande nmcli configure une interface en DHCP ?",
    options: [
      "nmcli connection modify ens3 ipv4.method dhcp",
      "nmcli connection modify ens3 ipv4.method dynamic",
      "nmcli connection modify ens3 ipv4.method auto",
      "nmcli connection modify ens3 ipv4.method automatic",
    ],
    correct: 2,
    explanation: "ipv4.method auto active le DHCP. ipv4.method manual active l IP statique.",
  },
  // --- VRAI / FAUX ---
  {
    id: 31,
    type: "vf",
    question: "Un demon Linux demarre automatiquement au boot sans intervention de l utilisateur.",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Un demon est configure pour demarrer au boot via systemctl enable. Il reste actif en permanence en arriere-plan.",
  },
  {
    id: 32,
    type: "vf",
    question: "systemctl enable demarre immediatement un service.",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. systemctl enable configure uniquement le demarrage automatique au boot. Pour demarrer immediatement il faut systemctl start.",
  },
  {
    id: 33,
    type: "vf",
    question: "La commande ip addr add est permanente apres redemarrage.",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. ip addr add est temporaire. Apres redemarrage la configuration est perdue.",
  },
  {
    id: 34,
    type: "vf",
    question: "nmcli sauvegarde la configuration reseau de maniere permanente.",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. nmcli modifie les fichiers de NetworkManager qui sont charges automatiquement au demarrage du systeme.",
  },
  {
    id: 35,
    type: "vf",
    question: "usermod -aG sudo user1 retire user1 de tous ses groupes existants.",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. L option -a (append) preserve les groupes existants. Sans -a, usermod -G sudo user1 retirerait user1 de tous ses autres groupes.",
  },
  {
    id: 36,
    type: "vf",
    question: "/etc/passwd contient les mots de passe chiffres des utilisateurs.",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. /etc/passwd contient les informations des utilisateurs mais pas les mots de passe. Les mots de passe chiffres sont dans /etc/shadow.",
  },
  {
    id: 37,
    type: "vf",
    question: "userdel -r supprime l utilisateur et son repertoire home.",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. userdel -r supprime le compte utilisateur ET son repertoire home. Sans -r, seul le compte est supprime.",
  },
  {
    id: 38,
    type: "vf",
    question: "La cle privee SSH doit etre copiee sur le serveur pour l authentification par cles.",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. C est la cle PUBLIQUE qui est copiee sur le serveur dans ~/.ssh/authorized_keys. La cle privee ne quitte jamais la machine cliente.",
  },
  {
    id: 39,
    type: "vf",
    question: "Sur Ubuntu Netplan, un fichier yaml avec permissions 644 peut causer un avertissement.",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Netplan exige chmod 600 sur ses fichiers YAML. Avec 644, il affiche un avertissement et peut refuser d appliquer la config.",
  },
  {
    id: 40,
    type: "vf",
    question: "Le groupe wheel sur Fedora et le groupe sudo sur Ubuntu ont le meme role.",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Les deux groupes donnent les privileges d administration (sudo). wheel est la convention Red Hat/Fedora, sudo est la convention Ubuntu/Debian.",
  },
];

export default function ConfigurationDeBaseLinuxServer() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — Configuration de Base Linux"
      courseLink="/idosr/linux/lesson-01"
    />
  );
}