import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  {
    id: 1,
    type: "qcm",
    question: "Quel repertoire contient les fichiers de configuration du systeme Linux ?",
    options: ["/bin", "/var", "/etc", "/usr"],
    correct: 2,
    explanation: "/etc est le repertoire standard des fichiers de configuration systeme. On y trouve nginx/, ssh/, hosts, fstab, crontab, passwd, etc.",
  },
  {
    id: 2,
    type: "qcm",
    question: "Ou sont stockes les repertoires personnels des utilisateurs ordinaires ?",
    options: ["/root", "/home", "/usr", "/srv"],
    correct: 1,
    explanation: "/home contient les repertoires personnels de chaque utilisateur. Exemple : /home/said, /home/omar.",
  },
  {
    id: 3,
    type: "qcm",
    question: "Quel repertoire est reserve exclusivement au superutilisateur root ?",
    options: ["/home/root", "/admin", "/root", "/etc/root"],
    correct: 2,
    explanation: "/root est le repertoire personnel de l utilisateur root. Il est distinct de /home et inaccessible aux utilisateurs ordinaires.",
  },
  {
    id: 4,
    type: "qcm",
    question: "Les fichiers de logs systeme et applications se trouvent dans :",
    options: ["/tmp", "/log", "/sys/log", "/var/log"],
    correct: 3,
    explanation: "/var/log contient tous les logs systeme et applicatifs : syslog, auth.log, nginx/access.log, dmesg, etc.",
  },
  {
    id: 5,
    type: "qcm",
    question: "Quel repertoire contient les binaires essentiels accessibles a tous les utilisateurs (ls, cp, mv) ?",
    options: ["/sbin", "/usr/bin", "/bin", "/opt"],
    correct: 2,
    explanation: "/bin contient les binaires essentiels pour tous les utilisateurs. /sbin est reserve aux binaires d administration systeme (root).",
  },
  {
    id: 6,
    type: "qcm",
    question: "Le repertoire /tmp est caracterise par :",
    options: [
      "Il contient les fichiers de configuration",
      "Son contenu est efface a chaque redemarrage",
      "Il est reserve a root uniquement",
      "Il contient les programmes installes",
    ],
    correct: 1,
    explanation: "/tmp contient des fichiers temporaires. Son contenu est automatiquement efface a chaque redemarrage du systeme.",
  },
  {
    id: 7,
    type: "qcm",
    question: "La racine web par defaut pour Apache/Nginx se trouve dans :",
    options: ["/srv/web", "/home/www", "/var/www", "/etc/www"],
    correct: 2,
    explanation: "/var/www est la racine web par defaut. On y trouve generalement le dossier html/ contenant les fichiers du site.",
  },
  {
    id: 8,
    type: "qcm",
    question: "Selon la norme FHS, quels repertoires sont statiques et partageables ?",
    options: [
      "/var, /tmp, /run",
      "/bin, /sbin, /lib, /usr, /opt",
      "/home, /root",
      "/etc, /dev",
    ],
    correct: 1,
    explanation: "Les repertoires statiques sont /bin, /sbin, /lib, /usr, /opt. Les repertoires variables sont /var, /tmp, /run.",
  },
  {
    id: 9,
    type: "qcm",
    question: "Quelle commande affiche le chemin absolu du repertoire courant ?",
    options: ["ls", "cd", "pwd", "dir"],
    correct: 2,
    explanation: "pwd = Print Working Directory. Elle affiche le chemin complet du repertoire dans lequel vous vous trouvez.",
  },
  {
    id: 10,
    type: "qcm",
    question: "Pour remonter d un niveau dans l arborescence, on utilise :",
    options: ["cd /", "cd -", "cd ~", "cd .."],
    correct: 3,
    explanation: "cd .. remonte d un niveau vers le repertoire parent. cd ../.. remonte de deux niveaux.",
  },
  {
    id: 11,
    type: "qcm",
    question: "La commande cd - permet de :",
    options: [
      "Aller a la racine",
      "Revenir au repertoire precedent",
      "Aller dans le repertoire personnel",
      "Remonter d un niveau",
    ],
    correct: 1,
    explanation: "cd - retourne au dernier repertoire visite. Tres utile pour alterner entre deux emplacements.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Quelle commande liste TOUS les fichiers y compris les fichiers caches, avec les details ?",
    options: ["ls -lhS", "ls -al", "ls -t", "ls -r"],
    correct: 1,
    explanation: "ls -al combine -a (all : affiche les fichiers caches commencant par .) et -l (long : format detaille avec droits, proprietaire, taille, date).",
  },
  {
    id: 13,
    type: "qcm",
    question: "Les fichiers caches sous Linux commencent par :",
    options: ["_ (underscore)", "~ (tilde)", ". (point)", "# (diese)"],
    correct: 2,
    explanation: "Sous Linux, tout fichier ou dossier commencant par un point (.) est cache. Exemple : .bashrc, .ssh, .config.",
  },
  {
    id: 14,
    type: "qcm",
    question: "La commande ls -lhS trie les fichiers par :",
    options: [
      "Date du plus recent au plus ancien",
      "Ordre alphabetique",
      "Taille decroissante",
      "Taille croissante",
    ],
    correct: 2,
    explanation: "-S trie par taille (Size) en ordre decroissant. -h affiche les tailles en format lisible (Ko, Mo, Go). -l donne les details.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Pour creer l arborescence /Ali/Formation/TPLinux en une seule commande, on utilise :",
    options: [
      "mkdir /Ali/Formation/TPLinux",
      "mkdir -r /Ali/Formation/TPLinux",
      "mkdir -p /Ali/Formation/TPLinux",
      "mkdir -f /Ali/Formation/TPLinux",
    ],
    correct: 2,
    explanation: "-p (parents) cree tous les repertoires intermediaires s ils n existent pas encore. Sans -p, la commande echoue si Ali ou Formation n existent pas.",
  },
  {
    id: 16,
    type: "qcm",
    question: "La commande rmdir peut supprimer :",
    options: [
      "N importe quel repertoire",
      "Uniquement les repertoires vides",
      "Uniquement les fichiers",
      "Les repertoires et leur contenu",
    ],
    correct: 1,
    explanation: "rmdir ne fonctionne que sur les repertoires vides. Pour supprimer un repertoire avec son contenu, utiliser rm -rf.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Pour copier recursivement le repertoire /monRep vers /ailleurs, on utilise :",
    options: [
      "cp /monRep /ailleurs",
      "cp -a /monRep /ailleurs",
      "cp -r /monRep /ailleurs",
      "cp -f /monRep /ailleurs",
    ],
    correct: 2,
    explanation: "-r (recursive) est obligatoire pour copier un repertoire et tout son contenu. Sans -r, cp refuse de copier un repertoire.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Quelle option de cp permet de copier en preservant les droits, dates et proprietaires ?",
    options: ["-r", "-i", "-a", "-u"],
    correct: 2,
    explanation: "-a (archive) preserve les droits, les dates, les proprietaires, les groupes et les liens symboliques. C est l equivalent de -dR --preserve=all.",
  },
  {
    id: 19,
    type: "qcm",
    question: "La commande mv stagiaire Formation permet de :",
    options: [
      "Copier le repertoire stagiaire dans Formation",
      "Renommer stagiaire en Formation",
      "Deplacer Formation dans stagiaire",
      "Creer un lien symbolique",
    ],
    correct: 1,
    explanation: "mv sans changer de repertoire renomme le fichier ou dossier. mv stagiaire Formation renomme stagiaire en Formation.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Pour supprimer le repertoire /tmp/LeRep et tout son contenu sans confirmation, on utilise :",
    options: [
      "rm /tmp/LeRep",
      "rmdir -r /tmp/LeRep",
      "rm -rf /tmp/LeRep",
      "rm -i /tmp/LeRep",
    ],
    correct: 2,
    explanation: "-r (recursive) supprime le repertoire et tout son contenu. -f (force) supprime sans demander de confirmation. Attention : irreversible !",
  },
  {
    id: 21,
    type: "qcm",
    question: "La commande touch monfichier.txt sur un fichier existant :",
    options: [
      "Supprime le fichier",
      "Efface son contenu",
      "Met a jour son horodatage",
      "Le renomme",
    ],
    correct: 2,
    explanation: "touch sur un fichier existant met a jour uniquement sa date de derniere modification. Sur un fichier inexistant, il le cree vide.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Quelle commande permet d afficher un fichier page par page avec navigation en arriere ?",
    options: ["cat", "more", "less", "head"],
    correct: 2,
    explanation: "less permet la navigation avant ET arriere, la recherche avec /motif, et quitter avec q. more ne permet que d avancer. Pour les fichiers longs, toujours preferer less.",
  },
  {
    id: 23,
    type: "qcm",
    question: "La commande cat -n monFichier affiche :",
    options: [
      "Le fichier sans les lignes vides",
      "Le fichier avec les numeros de lignes",
      "Le fichier en ordre inverse",
      "Le nombre de lignes du fichier",
    ],
    correct: 1,
    explanation: "-n numerote chaque ligne affichee a partir de 1. Utile pour referencer des lignes precises lors du debogage.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Pour surveiller un fichier de log en temps reel, on utilise :",
    options: [
      "tail monFichier",
      "tail -n monFichier",
      "tail -f monFichier",
      "less monFichier",
    ],
    correct: 2,
    explanation: "-f (follow) maintient le fichier ouvert et affiche les nouvelles lignes au fur et a mesure qu elles sont ajoutees. Indispensable pour le monitoring.",
  },
  {
    id: 25,
    type: "qcm",
    question: "L operateur >> dans une redirection :",
    options: [
      "Ecrase le fichier de destination",
      "Ajoute a la fin du fichier existant",
      "Cree un nouveau fichier uniquement",
      "Redirige l entree standard",
    ],
    correct: 1,
    explanation: ">> ajoute le contenu a la fin du fichier existant sans l ecraser. > lui ecrase le fichier (ou le cree s il n existe pas).",
  },
  {
    id: 26,
    type: "qcm",
    question: "La commande ls -al | grep doc utilise le symbole | pour :",
    options: [
      "Ecrire le resultat dans un fichier",
      "Comparer deux commandes",
      "Envoyer la sortie de ls comme entree de grep",
      "Executer les deux commandes en parallele",
    ],
    correct: 2,
    explanation: "Le pipe | chaine les commandes : la sortie standard de la commande gauche devient l entree standard de la commande droite.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Pour afficher les 20 premieres lignes d un fichier, on utilise :",
    options: [
      "tail -n 20 fichier",
      "head -n 20 fichier",
      "cat -20 fichier",
      "more -20 fichier",
    ],
    correct: 1,
    explanation: "head affiche le debut d un fichier. Par defaut 10 lignes. -n 20 en affiche 20. tail fait l inverse : il affiche la fin.",
  },
  {
    id: 28,
    type: "qcm",
    question: "La commande grep -i effectue une recherche :",
    options: [
      "Recursive dans les sous-repertoires",
      "Insensible a la casse",
      "En affichant les numeros de ligne",
      "En affichant uniquement le nombre de resultats",
    ],
    correct: 1,
    explanation: "-i (ignore case) rend la recherche insensible a la casse. root, ROOT et Root seront tous trouves.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Pour chercher le mot root dans /etc/passwd et afficher les numeros de lignes, on utilise :",
    options: [
      "grep root /etc/passwd",
      "grep -n root /etc/passwd",
      "grep -c root /etc/passwd",
      "grep -v root /etc/passwd",
    ],
    correct: 1,
    explanation: "-n (number) prefixe chaque ligne correspondante avec son numero. Tres utile pour localiser rapidement une entree.",
  },
  {
    id: 30,
    type: "qcm",
    question: "La commande grep -v root /etc/passwd affiche :",
    options: [
      "Toutes les lignes contenant root",
      "Toutes les lignes ne contenant PAS root",
      "Le nombre de lignes avec root",
      "La premiere ligne avec root",
    ],
    correct: 1,
    explanation: "-v (invert) inverse le filtre et affiche les lignes qui ne correspondent PAS au motif. Utile pour exclure certains resultats.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Pour chercher tous les fichiers .conf dans /etc, on utilise :",
    options: [
      "find /etc -type conf",
      "grep -r .conf /etc",
      "find /etc -name '*.conf'",
      "ls -r /etc/*.conf",
    ],
    correct: 2,
    explanation: "find avec -name '*.conf' recherche recursivement tous les fichiers dont le nom se termine par .conf. Le * est un joker.",
  },
  {
    id: 32,
    type: "qcm",
    question: "L option -mtime -5 dans la commande find recherche les fichiers :",
    options: [
      "Modifies il y a exactement 5 jours",
      "Modifies il y a plus de 5 jours",
      "Modifies dans les 5 derniers jours",
      "Accedes dans les 5 derniers jours",
    ],
    correct: 2,
    explanation: "-mtime -5 signifie modifie il y a moins de 5 jours. Le - signifie moins de. -atime concerne les dates d acces.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Pour chercher les fichiers appartenant a l utilisateur said, on utilise :",
    options: [
      "find . -group said",
      "find . -owner said",
      "find . -user said",
      "find . -name said",
    ],
    correct: 2,
    explanation: "-user filtre par proprietaire du fichier. -group filtre par groupe proprietaire. -owner n est pas une option valide de find.",
  },
  {
    id: 34,
    type: "qcm",
    question: "La difference entre un lien symbolique et un lien physique est :",
    options: [
      "Le lien physique peut pointer vers un repertoire, pas le symbolique",
      "Le lien symbolique est un raccourci pouvant pointer vers n importe quel chemin ; le lien physique partage le meme inode",
      "Il n y a aucune difference",
      "Le lien physique est supprime si le fichier source est supprime",
    ],
    correct: 1,
    explanation: "Le lien symbolique est un raccourci (comme .lnk Windows). Le lien physique partage le meme inode : si le fichier source est supprime, le lien physique survit car ils partagent les memes donnees.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Pour creer un lien symbolique nomme MonLien pointant vers /var/log/syslog, on utilise :",
    options: [
      "ln /var/log/syslog MonLien",
      "ln -s /var/log/syslog MonLien",
      "ln -f /var/log/syslog MonLien",
      "cp -l /var/log/syslog MonLien",
    ],
    correct: 1,
    explanation: "-s (symbolic) cree un lien symbolique. Sans -s, ln cree un lien physique. Le lien symbolique est indique par -> dans ls -la.",
  },
  {
    id: 36,
    type: "qcm",
    question: "Les permissions rwxr-xr-- en notation numerique correspondent a :",
    options: ["777", "755", "754", "644"],
    correct: 2,
    explanation: "rwx = 4+2+1 = 7, r-x = 4+0+1 = 5, r-- = 4+0+0 = 4. Donc rwxr-xr-- = 754.",
  },
  {
    id: 37,
    type: "qcm",
    question: "La commande chmod 600 monFichier donne les droits :",
    options: [
      "Lecture et ecriture au proprietaire uniquement",
      "Lecture seule a tout le monde",
      "Tous les droits au proprietaire",
      "Lecture et ecriture a tout le monde",
    ],
    correct: 0,
    explanation: "6 = rw- pour le proprietaire, 0 = --- pour le groupe, 0 = --- pour les autres. Utilise typiquement pour les cles SSH et fichiers prives.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Pour retirer le droit d ecriture aux autres de facon recursive sur /shared/docs, on utilise :",
    options: [
      "chmod -R 644 /shared/docs",
      "chmod -R o-w /shared/docs",
      "chmod -R g-w /shared/docs",
      "chown -R o-w /shared/docs",
    ],
    correct: 1,
    explanation: "o = others (autres), -w = retirer l ecriture, -R = recursif sur tout le contenu. g = group, u = user/proprietaire.",
  },
  {
    id: 39,
    type: "qcm",
    question: "La commande chown -R said:TRI monRep permet de :",
    options: [
      "Changer uniquement le groupe du repertoire monRep",
      "Changer le proprietaire en said et le groupe en TRI de monRep et tout son contenu",
      "Changer les permissions de monRep recursivement",
      "Ajouter said au groupe TRI",
    ],
    correct: 1,
    explanation: "chown user:groupe change proprietaire ET groupe. -R applique le changement recursivement sur tout le contenu du repertoire.",
  },
  {
    id: 40,
    type: "qcm",
    question: "La commande su - (avec le tiret) par rapport a su (sans tiret) :",
    options: [
      "N a aucune difference",
      "Charge l environnement complet de root (PATH, variables...)",
      "Demande un mot de passe supplementaire",
      "Ouvre un shell restreint",
    ],
    correct: 1,
    explanation: "su - charge l environnement complet de root : PATH, variables d environnement, repertoire courant (/root). su seul garde l environnement de l utilisateur courant.",
  },
];

export default function LinuxBasicsQuiz() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — Commandes de Base Linux"
      courseLink="/idosr/linux/lesson-00"
    />
  );
}