import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  // ─── Section 1 : Vrai / Faux (10 questions) ───────────────────────────────

  {
    id: 1,
    type: "vf",
    question: "Sans activer ip_forward, un serveur Linux peut router les paquets entre ses interfaces reseau ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Sans 'ip_forward = 1', Linux se comporte comme un simple hote et ne transfere pas les paquets entre ses interfaces. Il faut obligatoirement activer le forwarding IP pour qu'il fonctionne comme un routeur.",
  },
  {
    id: 2,
    type: "vf",
    question: "La commande 'echo 1 > /proc/sys/net/ipv4/ip_forward' active le forwarding IP de facon permanente ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Cette commande active le forwarding IP de facon temporaire. La modification est perdue au prochain redemarrage. Pour le rendre permanent, il faut modifier /etc/sysctl.conf et executer 'sysctl -p'.",
  },
  {
    id: 3,
    type: "vf",
    question: "La commande 'ip route show' et 'route -n' affichent la meme table de routage ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Les deux commandes affichent la table de routage du noyau Linux. 'ip route show' est la commande moderne recommandee, tandis que 'route -n' est la commande classique legacy.",
  },
  {
    id: 4,
    type: "vf",
    question: "Une route ajoutee avec 'ip route add' persiste apres un redemarrage du systeme ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Les routes ajoutees avec 'ip route add' sont temporaires et disparaissent au redemarrage. Pour les rendre permanentes, il faut les configurer via Netplan (Ubuntu) ou NetworkManager (Fedora).",
  },
  {
    id: 5,
    type: "vf",
    question: "FRR (Free Range Routing) remplace Quagga comme logiciel de routage dynamique sous Linux ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. FRR est le successeur de Quagga, cree par les memes developpeurs avec l'objectif d'ameliorer et moderniser le projet. Quagga n'est plus disponible dans les depots officiels des dernieres versions d'Ubuntu.",
  },
  {
    id: 6,
    type: "vf",
    question: "OSPF est un protocole de routage a vecteur de distance ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. OSPF (Open Shortest Path First) est un protocole a etat de lien (link-state). C'est RIP qui est un protocole a vecteur de distance. OSPF est plus performant et adapte aux infrastructures hierarchiques.",
  },
  {
    id: 7,
    type: "vf",
    question: "Le NAT Masquerading modifie l'adresse source des paquets sortants ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Le masquerading (SNAT dynamique) remplace l'adresse IP source des paquets sortants par l'adresse IP de la passerelle, permettant aux machines du reseau local d'acceder a internet.",
  },
  {
    id: 8,
    type: "vf",
    question: "La commande 'vtysh' permet d'acceder a l'interface de configuration de FRR ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. vtysh est l'interface en ligne de commande de FRR, similaire aux routeurs Cisco. Elle permet de configurer les protocoles de routage dynamique (OSPF, RIP, BGP) de maniere interactive.",
  },
  {
    id: 9,
    type: "vf",
    question: "RIP est limite a un maximum de 15 sauts entre la source et la destination ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. RIP utilise le nombre de sauts (hops) comme metrique et est limite a 15 sauts maximum. Un reseau a 16 sauts est considere comme inaccessible. C'est l'une des raisons pour lesquelles RIP est obsolete.",
  },
  {
    id: 10,
    type: "vf",
    question: "Le DNAT modifie l'adresse destination des paquets entrants ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Le DNAT (Destination NAT) modifie l'adresse de destination des paquets entrants pour les rediriger vers une machine interne. C'est utile pour exposer un serveur interne via la passerelle.",
  },

  // ─── Section 2 : QCM (30 questions) ───────────────────────────────────────

  {
    id: 11,
    type: "qcm",
    question: "Quelle commande active le forwarding IP de facon permanente sous Linux ?",
    options: [
      "echo 1 > /proc/sys/net/ipv4/ip_forward",
      "sudo sysctl net.ipv4.ip_forward=1",
      "Modifier net.ipv4.ip_forward = 1 dans /etc/sysctl.conf puis sudo sysctl -p",
      "sudo ip forward enable",
    ],
    correct: 2,
    explanation: "Pour rendre le forwarding permanent, il faut modifier /etc/sysctl.conf en ajoutant 'net.ipv4.ip_forward = 1', puis appliquer avec 'sudo sysctl -p'. Sans cette etape, la modification est perdue au redemarrage.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Quelle commande affiche la table de routage avec la methode moderne recommandee ?",
    options: [
      "route -n",
      "netstat -r",
      "ip route show",
      "ifconfig route",
    ],
    correct: 2,
    explanation: "'ip route show' est la commande moderne issue du paquet iproute2. Elle remplace 'route -n' qui est consideree comme legacy. Les deux affichent la meme table mais 'ip route show' offre une sortie plus lisible.",
  },
  {
    id: 13,
    type: "qcm",
    question: "Quelle commande ajoute une route vers le reseau 10.0.0.0/8 via la passerelle 192.168.1.1 ?",
    options: [
      "sudo route add 10.0.0.0/8 gw 192.168.1.1",
      "sudo ip route add 10.0.0.0/8 via 192.168.1.1",
      "sudo ip route set 10.0.0.0/8 gateway 192.168.1.1",
      "sudo routing add 10.0.0.0/8 192.168.1.1",
    ],
    correct: 1,
    explanation: "La syntaxe correcte avec iproute2 est 'ip route add RESEAU via PASSERELLE'. L'ancienne commande 'route add' est obsolete et n'est plus recommandee.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Quelle commande supprime la route par defaut via 192.168.1.1 ?",
    options: [
      "sudo ip route remove default",
      "sudo ip route del default via 192.168.1.1",
      "sudo ip route flush default",
      "sudo route del 0.0.0.0",
    ],
    correct: 1,
    explanation: "'ip route del default via PASSERELLE' supprime la route par defaut. On peut aussi utiliser 'ip route del default' sans specifier la passerelle si une seule route par defaut existe.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Dans la table de routage, que signifie une passerelle affichant '0.0.0.0' ?",
    options: [
      "La route est desactivee",
      "Le reseau est directement connecte (pas de routeur intermediaire)",
      "La route par defaut est utilisee",
      "Le reseau est inaccessible",
    ],
    correct: 1,
    explanation: "Une passerelle '0.0.0.0' signifie que le reseau est directement connecte a une interface du routeur — aucun routeur intermediaire n'est necessaire pour l'atteindre.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Quelle regle iptables permet le masquerading sur l'interface eth0 ?",
    options: [
      "sudo iptables -A FORWARD -o eth0 -j MASQUERADE",
      "sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE",
      "sudo iptables -t filter -A OUTPUT -o eth0 -j MASQUERADE",
      "sudo iptables -t nat -A PREROUTING -o eth0 -j MASQUERADE",
    ],
    correct: 1,
    explanation: "Le masquerading utilise la table 'nat', la chaine 'POSTROUTING' (apres le routage), et la cible 'MASQUERADE' qui remplace dynamiquement l'IP source par celle de l'interface de sortie.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Quelle regle iptables redirige les connexions sur le port 80 vers le serveur 192.168.1.10 ?",
    options: [
      "sudo iptables -t nat -A POSTROUTING -p tcp --dport 80 -j DNAT --to 192.168.1.10",
      "sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to 192.168.1.10",
      "sudo iptables -A FORWARD -p tcp --dport 80 -j REDIRECT --to 192.168.1.10",
      "sudo iptables -t nat -A INPUT -p tcp --dport 80 -j DNAT --to 192.168.1.10",
    ],
    correct: 1,
    explanation: "Le DNAT utilise la table 'nat' et la chaine 'PREROUTING' (avant le routage). Cela modifie l'adresse de destination avant que le paquet soit route vers sa destination.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Sur Ubuntu, comment rendre une route statique permanente via Netplan ?",
    options: [
      "Ajouter la route dans /etc/network/interfaces",
      "Ajouter une section 'routes' dans /etc/netplan/*.yaml puis 'netplan apply'",
      "Executer 'ip route add' au demarrage dans /etc/rc.local",
      "Modifier /etc/sysconfig/network-scripts/route-eth0",
    ],
    correct: 1,
    explanation: "Sur Ubuntu Server, Netplan est le gestionnaire reseau par defaut. Les routes permanentes se configurent dans le fichier YAML de Netplan sous la cle 'routes', puis on applique avec 'sudo netplan apply'.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Quelle commande installe FRR sur Ubuntu ?",
    options: [
      "sudo apt install quagga -y",
      "sudo apt install bird -y",
      "sudo apt install frr -y",
      "sudo apt install frrouting -y",
    ],
    correct: 2,
    explanation: "Le paquet s'appelle 'frr' sur Ubuntu/Debian. Sur Fedora/Red Hat, la commande est 'sudo dnf install frr -y'. Quagga n'est plus disponible dans les depots modernes.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Dans quel fichier FRR active-t-on le demon OSPF ?",
    options: [
      "/etc/frr/frr.conf",
      "/etc/frr/ospf.conf",
      "/etc/frr/daemons",
      "/etc/sysconfig/frr",
    ],
    correct: 2,
    explanation: "Le fichier /etc/frr/daemons liste tous les demons FRR et leur etat. Pour activer OSPF, on change 'ospfd=no' en 'ospfd=yes', puis on redemarree FRR.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Quelle commande permet d'acceder a l'interface de configuration de FRR ?",
    options: [
      "sudo frr-cli",
      "sudo frr configure",
      "sudo vtysh",
      "sudo birdc",
    ],
    correct: 2,
    explanation: "vtysh est l'interface de commande unifiee de FRR. Elle donne acces a tous les demons FRR (OSPF, RIP, BGP) dans une seule invite de commande, similaire aux routeurs Cisco IOS.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Dans vtysh, quelle commande entre en mode configuration du routeur ?",
    options: [
      "enable",
      "config",
      "configure terminal",
      "router config",
    ],
    correct: 2,
    explanation: "'configure terminal' (ou 'conf t') fait passer en mode configuration globale dans vtysh, identique a Cisco IOS. C'est le mode depuis lequel on configure les protocoles de routage.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Dans vtysh en mode OSPF, quelle commande declare le reseau 192.168.1.0/24 dans la zone backbone ?",
    options: [
      "network 192.168.1.0/24",
      "network 192.168.1.0/24 area 0",
      "ospf network 192.168.1.0/24 area backbone",
      "add network 192.168.1.0/24 area 0",
    ],
    correct: 1,
    explanation: "La commande 'network X.X.X.X/X area 0' declare un reseau dans la zone OSPF backbone (area 0). Toutes les zones OSPF doivent etre connectees a area 0.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Dans vtysh, quelle commande sauvegarde la configuration FRR ?",
    options: [
      "save",
      "copy running-config startup-config",
      "write memory",
      "config save",
    ],
    correct: 2,
    explanation: "'write memory' sauvegarde la configuration en cours dans le fichier /etc/frr/frr.conf. Sans cette commande, la configuration est perdue au redemarrage de FRR.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Quelle commande vtysh affiche les voisins OSPF et leur etat ?",
    options: [
      "show ospf",
      "show ip ospf neighbor",
      "show ospf adjacency",
      "display ospf peers",
    ],
    correct: 1,
    explanation: "'show ip ospf neighbor' affiche tous les voisins OSPF avec leur etat. L'etat 'Full' indique une adjacence etablie correctement. Les etats 'ExStart' ou '2-Way' indiquent un probleme.",
  },
  {
    id: 26,
    type: "qcm",
    question: "Quelle est la difference principale entre OSPF et RIP ?",
    options: [
      "OSPF utilise le nombre de sauts comme metrique, RIP utilise la bande passante",
      "OSPF est a etat de lien avec convergence rapide, RIP est a vecteur de distance avec convergence lente",
      "OSPF est limite a 15 sauts, RIP est illimite",
      "OSPF est proprietaire Cisco, RIP est standard ouvert",
    ],
    correct: 1,
    explanation: "OSPF (link-state) maintient une carte complete du reseau et converge rapidement. RIP (distance-vector) echange des tables de routage completes et converge lentement (jusqu'a 180s). RIP est limite a 15 sauts, OSPF est illimite.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Dans quel fichier configure-t-on une route permanente sur Fedora avec NetworkManager ?",
    options: [
      "/etc/netplan/00-installer-config.yaml",
      "/etc/network/interfaces",
      "/etc/sysconfig/network-scripts/route-INTERFACE",
      "/etc/NetworkManager/routes.conf",
    ],
    correct: 2,
    explanation: "Sur Fedora/Red Hat, les routes permanentes se configurent dans /etc/sysconfig/network-scripts/route-NOM_INTERFACE (ex: route-eth0). On redemarree ensuite NetworkManager pour appliquer.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Quelle commande trace le chemin des paquets vers une destination ?",
    options: [
      "ping -t 192.168.1.1",
      "ip route trace 192.168.1.1",
      "traceroute 192.168.1.1",
      "pathfind 192.168.1.1",
    ],
    correct: 2,
    explanation: "'traceroute' affiche chaque routeur (saut) traverse pour atteindre la destination, avec le temps de reponse de chaque saut. C'est l'outil principal pour diagnostiquer les problemes de routage.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Quelle commande affiche la table ARP du systeme ?",
    options: [
      "ip neigh show",
      "arp -a",
      "ip arp list",
      "show arp",
    ],
    correct: 0,
    explanation: "'ip neigh show' affiche la table ARP avec les correspondances IP/MAC des machines recemment contactees. C'est la commande moderne qui remplace 'arp -a'.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Dans quel scenario utilise-t-on le DNAT ?",
    options: [
      "Pour permettre au reseau local d'acceder a internet",
      "Pour rediriger le trafic entrant vers un serveur interne",
      "Pour equilibrer la charge entre plusieurs serveurs",
      "Pour bloquer les connexions non autorisees",
    ],
    correct: 1,
    explanation: "Le DNAT (Destination NAT) modifie l'adresse de destination des paquets entrants pour les rediriger vers un serveur interne. Par exemple, toutes les connexions HTTP arrivant sur la passerelle peuvent etre redirigees vers un serveur web interne.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Quelle est la route par defaut en notation CIDR ?",
    options: [
      "127.0.0.1/8",
      "0.0.0.0/0",
      "255.255.255.255/32",
      "192.168.0.0/16",
    ],
    correct: 1,
    explanation: "La route par defaut est '0.0.0.0/0' — elle correspond a toutes les destinations. Elle est utilisee quand aucune autre route plus specifique ne correspond au paquet a router.",
  },
  {
    id: 32,
    type: "qcm",
    question: "Quelle commande vtysh active la propagation de la route par defaut en OSPF ?",
    options: [
      "redistribute default",
      "default-information originate",
      "export default route",
      "ospf propagate default",
    ],
    correct: 1,
    explanation: "'default-information originate' en mode configuration OSPF indique au routeur de propager sa route par defaut vers tous ses voisins OSPF. C'est utile pour centraliser la sortie vers internet.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Quelle commande vtysh affiche toutes les routes apprises (statiques + dynamiques) ?",
    options: [
      "show route all",
      "display ip routing-table",
      "show ip route",
      "ip route show full",
    ],
    correct: 2,
    explanation: "'show ip route' dans vtysh affiche la table de routage complete avec les routes statiques (S), OSPF (O), RIP (R) et directement connectees (C). C'est l'equivalent de 'ip route show' en dehors de vtysh.",
  },
  {
    id: 34,
    type: "qcm",
    question: "Pourquoi RIP est-il considere comme obsolete en production ?",
    options: [
      "Parce qu'il ne supporte pas IPv4",
      "Parce qu'il est limite a 15 sauts, converge lentement et genere beaucoup de trafic",
      "Parce qu'il n'est plus supporte par FRR",
      "Parce qu'il necessite une licence commerciale",
    ],
    correct: 1,
    explanation: "RIP est obsolete car il est limite a 15 sauts maximum, sa convergence peut prendre jusqu'a 180 secondes, et il envoie periodiquement sa table de routage complete — ce qui genere une charge reseau inutile. OSPF n'a pas ces limitations.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Quelle commande vtysh active la configuration du protocole RIP ?",
    options: [
      "router rip enable",
      "protocol rip",
      "router rip",
      "enable rip",
    ],
    correct: 2,
    explanation: "Dans vtysh, 'router rip' en mode configuration globale entre dans le mode de configuration RIP. C'est la meme syntaxe que pour OSPF ('router ospf').",
  },
  {
    id: 36,
    type: "qcm",
    question: "Quelle commande vtysh affiche les routes apprises via RIP ?",
    options: [
      "show rip routes",
      "show ip rip",
      "display rip table",
      "show routing rip",
    ],
    correct: 1,
    explanation: "'show ip rip' affiche la table RIP avec les reseaux appris, leurs metriques (nombre de sauts) et les adresses des voisins qui ont annonce ces routes.",
  },
  {
    id: 37,
    type: "qcm",
    question: "Quelle est la fonction de 'redistribute connected' dans la configuration FRR ?",
    options: [
      "Partager les routes apprises dynamiquement avec les voisins",
      "Distribuer les reseaux directement connectes aux interfaces du routeur",
      "Redistribuer les routes statiques dans le protocole dynamique",
      "Connecter plusieurs instances FRR entre elles",
    ],
    correct: 1,
    explanation: "'redistribute connected' annonce automatiquement les reseaux directement connectes aux interfaces du routeur via le protocole de routage dynamique (OSPF ou RIP). Sans cela, les voisins ne connaitraient pas ces reseaux.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Dans la commande 'network 192.168.1.0/24 area 0' en OSPF, que signifie 'area 0' ?",
    options: [
      "C'est le numero de la table de routage",
      "C'est la zone backbone OSPF a laquelle appartient ce reseau",
      "C'est la priorite du reseau dans l'algorithme SPF",
      "C'est l'identifiant de l'interface reseau",
    ],
    correct: 1,
    explanation: "Area 0 est la zone backbone OSPF. Toutes les autres zones OSPF doivent etre connectees a area 0. Dans un reseau simple, tous les reseaux peuvent etre dans area 0.",
  },
  {
    id: 39,
    type: "qcm",
    question: "Quelle commande verifie que le fichier sysctl.conf a bien ete applique ?",
    options: [
      "sudo sysctl --check",
      "sudo sysctl -p",
      "cat /etc/sysctl.conf",
      "sudo systemctl status sysctl",
    ],
    correct: 1,
    explanation: "'sudo sysctl -p' relit et applique le fichier /etc/sysctl.conf. Il affiche aussi les parametres appliques, ce qui permet de verifier que net.ipv4.ip_forward = 1 est bien actif.",
  },
  {
    id: 40,
    type: "qcm",
    question: "Quelle est la difference entre SNAT et DNAT ?",
    options: [
      "SNAT est pour IPv4, DNAT est pour IPv6",
      "SNAT modifie l'adresse source des paquets sortants, DNAT modifie l'adresse destination des paquets entrants",
      "SNAT est statique, DNAT est dynamique",
      "SNAT bloque les connexions, DNAT les autorise",
    ],
    correct: 1,
    explanation: "SNAT (Source NAT) modifie l'IP source des paquets sortants — utile pour permettre au reseau local d'acceder a internet. DNAT (Destination NAT) modifie l'IP destination des paquets entrants — utile pour rediriger le trafic vers un serveur interne.",
  },
];

export default function QuizzRoutage() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — Routage sous Linux"
      courseLink="/docs/linux/lesson-08"
    />
  );
}