import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  // ─── Section 1 : Vrai / Faux (10 questions) ───────────────────────────────

  {
    id: 1,
    type: "vf",
    question: "Apache HTTP Server est un logiciel proprietaire qui necessite une licence payante ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Apache est un logiciel libre et gratuit, distribue sous la licence Apache License.",
  },
  {
    id: 2,
    type: "vf",
    question: "Le port 80 est utilise par Apache pour les connexions HTTP non chiffrees ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Apache ecoute par defaut sur le port 80 pour HTTP et sur le port 443 pour HTTPS.",
  },
  {
    id: 3,
    type: "vf",
    question: "Sur Ubuntu, le nom du service Apache est 'httpd' ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Sur Ubuntu/Debian, le service s'appelle 'apache2'. C'est 'httpd' sur Fedora/Red Hat.",
  },
  {
    id: 4,
    type: "vf",
    question: "Il est recommande de modifier directement le fichier apache2.conf pour configurer un nouveau site ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Il est fortement recommande de creer des fichiers separes dans sites-available/ et de ne jamais modifier apache2.conf directement.",
  },
  {
    id: 5,
    type: "vf",
    question: "La commande 'a2ensite' permet d'activer un site virtuel sur Ubuntu/Debian ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. La commande 'a2ensite monsite.conf' cree un lien symbolique dans sites-enabled/ pour activer le site.",
  },
  {
    id: 6,
    type: "vf",
    question: "Un seul serveur Apache peut heberger plusieurs sites web differents grace aux VirtualHosts ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Apache supporte les sites virtuels (VirtualHost) permettant d'heberger plusieurs sites sur un meme serveur.",
  },
  {
    id: 7,
    type: "vf",
    question: "La directive DocumentRoot definit le nom de domaine du site web ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. DocumentRoot definit le chemin vers les fichiers du site. C'est ServerName qui definit le nom de domaine.",
  },
  {
    id: 8,
    type: "vf",
    question: "Le code HTTP 403 signifie que le fichier demande est introuvable ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Le code 403 signifie 'Acces refuse' (probleme de permissions). C'est le code 404 qui signifie 'fichier introuvable'.",
  },
{
  id: 9,
  type: "vf",
  question: "La commande 'systemctl reload apache2' recharge la configuration sans interrompre les connexions actives ?",
  options: ["Vrai", "Faux"],
  correct: 0,
  explanation: "VRAI. reload relit les fichiers de configuration a chaud. Contrairement a restart qui coupe et redemarree le service en interrompant les connexions en cours.",
},
  {
    id: 10,
    type: "vf",
    question: "La methode Name-based VirtualHost necessite plusieurs adresses IP sur le serveur ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. La methode Name-based fonctionne avec une seule IP. Apache distingue les sites grace au champ ServerName envoye par le navigateur.",
  },

  // ─── Section 2 : QCM (30 questions) ──────────────────────────────────────

{
  id: 11,
  type: "qcm",
  question: "Quelle est la procedure complete et dans le bon ordre pour creer un site virtuel Apache fonctionnel ?",
  options: [
    "Creer le VirtualHost → Installer Apache → Creer les fichiers du site → Activer le site → Configurer le DNS",
    "Installer Apache → Creer les fichiers du site → Definir les permissions → Creer le VirtualHost → Activer le site → Configurer le DNS",
    "Configurer le DNS → Installer Apache → Creer le VirtualHost → Creer les fichiers du site → Activer le site",
    "Installer Apache → Creer le VirtualHost → Activer le site → Creer les fichiers du site → Configurer le DNS",
  ],
  correct: 1,
  explanation: "L'ordre correct est : (1) Installer Apache et demarrer le service, (2) Creer le dossier du site et index.html, (3) Definir les permissions chown/chmod, (4) Creer le fichier VirtualHost dans sites-available/, (5) Activer avec a2ensite et recharger Apache, (6) Ajouter l'enregistrement A dans Bind9.",
},
  {
    id: 12,
    type: "qcm",
    question: "Sur Ubuntu/Debian, quelle commande installe Apache ?",
    options: [
      "sudo dnf install httpd -y",
      "sudo apt install apache2 -y",
      "sudo yum install apache -y",
      "sudo apt install httpd -y",
    ],
    correct: 1,
    explanation: "Sur Ubuntu/Debian, le paquet s'appelle 'apache2' et s'installe avec apt. Sur Fedora/Red Hat, le paquet est 'httpd' et s'installe avec dnf.",
  },
  {
    id: 13,
    type: "qcm",
    question: "Quel fichier contient la configuration principale d'Apache sur Fedora/Red Hat ?",
    options: [
      "/etc/apache2/apache2.conf",
      "/etc/httpd/conf.d/httpd.conf",
      "/etc/httpd/conf/httpd.conf",
      "/var/www/html/httpd.conf",
    ],
    correct: 2,
    explanation: "Sur Fedora/Red Hat, le fichier principal de configuration est /etc/httpd/conf/httpd.conf. Sur Ubuntu, c'est /etc/apache2/apache2.conf.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Quel dossier contient les fichiers de configuration des sites sur Ubuntu ?",
    options: [
      "/etc/apache2/sites-enabled/",
      "/etc/apache2/sites-available/",
      "/etc/apache2/conf.d/",
      "/var/www/sites/",
    ],
    correct: 1,
    explanation: "sites-available/ contient tous les fichiers de configuration des sites (actifs ou non). sites-enabled/ contient uniquement des liens symboliques vers les sites actifs.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Quelle directive Apache definit le chemin vers les fichiers du site web ?",
    options: [
      "ServerRoot",
      "ServerName",
      "DocumentRoot",
      "DirectoryIndex",
    ],
    correct: 2,
    explanation: "DocumentRoot definit le chemin vers les fichiers HTML/PHP du site. Par exemple : DocumentRoot /var/www/site1.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Quelle commande permet de tester la syntaxe de la configuration Apache ?",
    options: [
      "sudo apache2 --test",
      "sudo apachectl configtest",
      "sudo systemctl test apache2",
      "sudo apache2ctl -v",
    ],
    correct: 1,
    explanation: "La commande 'sudo apachectl configtest' verifie la syntaxe de tous les fichiers de configuration sans redemarrer Apache.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Sur Ubuntu, quelle commande active un site virtuel Apache ?",
    options: [
      "sudo apache2 enable site1.conf",
      "sudo systemctl enable site1",
      "sudo a2ensite site1.conf",
      "sudo ln -s site1.conf sites-enabled/",
    ],
    correct: 2,
    explanation: "La commande 'a2ensite' (Apache 2 Enable Site) cree automatiquement le lien symbolique dans sites-enabled/. 'a2dissite' fait l'inverse.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Quel fichier centralise les ports d'ecoute Apache sur Ubuntu ?",
    options: [
      "/etc/apache2/apache2.conf",
      "/etc/apache2/ports.conf",
      "/etc/apache2/sites-available/default.conf",
      "/etc/apache2/conf.d/listen.conf",
    ],
    correct: 1,
    explanation: "Le fichier /etc/apache2/ports.conf est prevu pour centraliser toutes les directives Listen. On n'ecrit jamais Listen dans chaque fichier de site.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Dans un VirtualHost, que signifie la syntaxe '<VirtualHost *:80>' ?",
    options: [
      "Le site ecoute uniquement sur l'IP 192.168.1.1 port 80",
      "Le site ecoute sur toutes les interfaces reseau sur le port 80",
      "Le site ecoute sur tous les ports de l'IP principale",
      "Le site ecoute uniquement sur localhost port 80",
    ],
    correct: 1,
    explanation: "L'asterisque (*) signifie 'toutes les interfaces reseau disponibles'. C'est la syntaxe recommandee pour la methode Name-based VirtualHost.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Quel est l'utilisateur proprietaire des fichiers web sur Ubuntu ?",
    options: [
      "root",
      "apache",
      "www-data",
      "httpd",
    ],
    correct: 2,
    explanation: "Sur Ubuntu/Debian, Apache s'execute sous l'utilisateur 'www-data'. Sur Fedora/Red Hat, l'utilisateur est 'apache'.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Quelle commande affiche en temps reel les erreurs Apache sur Ubuntu ?",
    options: [
      "sudo cat /var/log/apache2/error.log",
      "sudo tail -f /var/log/apache2/error.log",
      "sudo journalctl apache2",
      "sudo apache2 --log",
    ],
    correct: 1,
    explanation: "La commande 'tail -f' affiche les dernieres lignes d'un fichier et se met a jour en temps reel. C'est l'outil ideal pour surveiller les journaux.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Que signifie le code HTTP 500 ?",
    options: [
      "Fichier introuvable",
      "Acces refuse",
      "Erreur interne du serveur",
      "Redirection permanente",
    ],
    correct: 2,
    explanation: "Le code 500 (Internal Server Error) indique une erreur cote serveur : probleme de configuration, script defaillant ou permission incorrecte.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Quelle methode de VirtualHost est recommandee pour heberger plusieurs sites sur une seule IP ?",
    options: [
      "VirtualHost base sur le port",
      "VirtualHost base sur l'adresse IP",
      "VirtualHost base sur le nom (Name-based)",
      "VirtualHost base sur le protocole",
    ],
    correct: 2,
    explanation: "La methode Name-based est recommandee car elle ne necessite ni plusieurs ports ni plusieurs IPs. Apache utilise le champ ServerName de la requete HTTP pour router vers le bon site.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Quelle directive Apache autorise l'acces a un dossier pour tous les clients ?",
    options: [
      "Allow from all",
      "Require all granted",
      "AllowOverride All",
      "Options Indexes",
    ],
    correct: 1,
    explanation: "Dans Apache 2.4, la directive correcte est 'Require all granted' dans un bloc <Directory>. L'ancienne syntaxe 'Allow from all' est obsolete depuis Apache 2.4.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Sur Fedora/Red Hat, comment ouvrir le port HTTP dans le pare-feu de facon permanente ?",
    options: [
      "sudo ufw allow 80/tcp",
      "sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT",
      "sudo firewall-cmd --permanent --add-service=http",
      "sudo firewall-cmd --add-port=80",
    ],
    correct: 2,
    explanation: "Sur Fedora/Red Hat, firewalld est le pare-feu par defaut. L'option --permanent rend la regle persistante apres redemarrage. Il faut ensuite recharger avec --reload.",
  },
  {
    id: 26,
    type: "qcm",
    question: "Quelle est la permission correcte pour le dossier DocumentRoot afin qu'Apache puisse lire les fichiers ?",
    options: [
      "777",
      "644",
      "755",
      "700",
    ],
    correct: 2,
    explanation: "La permission 755 donne au proprietaire le droit de lire/ecrire/executer, et aux autres (dont Apache) le droit de lire et executer. C'est le minimum requis pour servir des fichiers web.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Quelle commande nmcli ajoute une deuxieme adresse IP sur l'interface eth0 ?",
    options: [
      "sudo nmcli connection add eth0 192.168.1.100/24",
      "sudo nmcli connection modify eth0 +ipv4.addresses 192.168.1.100/24",
      "sudo nmcli ip add 192.168.1.100 dev eth0",
      "sudo nmcli set eth0 ip 192.168.1.100",
    ],
    correct: 1,
    explanation: "La syntaxe correcte est 'nmcli connection modify NOM_CONNEXION +ipv4.addresses IP/MASQUE'. Le '+' ajoute sans remplacer les adresses existantes.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Quel enregistrement DNS faut-il creer pour associer un nom de domaine a l'IP du serveur Apache ?",
    options: [
      "Enregistrement MX",
      "Enregistrement CNAME",
      "Enregistrement A",
      "Enregistrement PTR",
    ],
    correct: 2,
    explanation: "L'enregistrement A (Address) associe un nom d'hote a une adresse IPv4. Par exemple : www IN A 192.168.1.1.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Quel fichier journal Apache contient toutes les requetes recues par le serveur ?",
    options: [
      "error.log",
      "debug.log",
      "access.log",
      "request.log",
    ],
    correct: 2,
    explanation: "Le fichier access.log (ou access_log sur Fedora) enregistre toutes les requetes HTTP : IP client, URL demandee, code de reponse et taille de la reponse.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Quelle commande recharge la configuration Apache sans couper les connexions en cours sur Ubuntu ?",
    options: [
      "sudo systemctl restart apache2",
      "sudo systemctl stop apache2",
      "sudo systemctl reload apache2",
      "sudo apachectl restart",
    ],
    correct: 2,
    explanation: "La commande 'reload' relit les fichiers de configuration sans interrompre les connexions actives. 'restart' coupe et redemarree le service, ce qui interrompt les connexions en cours.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Dans quel dossier doit-on placer les fichiers HTML d'un site sur Fedora/Red Hat ?",
    options: [
      "/etc/httpd/html/",
      "/var/www/html/",
      "/srv/http/",
      "/home/apache/html/",
    ],
    correct: 1,
    explanation: "Le dossier par defaut pour les fichiers web est /var/www/html/ sur les deux distributions. Il peut etre change via la directive DocumentRoot.",
  },
  {
    id: 32,
    type: "qcm",
    question: "Que signifie le code HTTP 301 ?",
    options: [
      "Requete acceptee et en cours de traitement",
      "Redirection permanente vers une autre URL",
      "Contenu non modifie depuis la derniere requete",
      "Redirection temporaire vers une autre URL",
    ],
    correct: 1,
    explanation: "Le code 301 (Moved Permanently) indique que la ressource a ete definitivement deplacee vers une nouvelle URL. Le navigateur met a jour ses favoris automatiquement.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Quelle directive Apache definit le nom de domaine du site dans un VirtualHost ?",
    options: [
      "DocumentRoot",
      "ServerAlias",
      "ServerName",
      "HostName",
    ],
    correct: 2,
    explanation: "La directive ServerName definit le nom de domaine principal du site (ex: ServerName www.site1.ma). ServerAlias permet d'ajouter des noms alternatifs.",
  },
  {
    id: 34,
    type: "qcm",
    question: "Quelle commande permet de verifier les interfaces reseau et leurs adresses IP ?",
    options: [
      "ifconfig -a",
      "ip addr show",
      "netstat -i",
      "route -n",
    ],
    correct: 1,
    explanation: "La commande 'ip addr show' est la methode moderne et recommandee pour afficher les interfaces reseau et leurs adresses IP. Elle remplace l'ancienne commande 'ifconfig'.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Quel est l'avantage principal de la methode VirtualHost par port par rapport aux autres methodes ?",
    options: [
      "Elle necessite moins de configuration DNS",
      "Elle permet d'utiliser un seul port pour plusieurs sites",
      "Elle fonctionne sans modifier le pare-feu",
      "Elle ne necessite pas de redemarrage Apache",
    ],
    correct: 0,
    explanation: "La methode par port ne necessite qu'une seule adresse IP et une seule entree DNS. Le client choisit le site en precisant le port dans l'URL (ex: http://site.ma:8080).",
  },
  {
    id: 36,
    type: "qcm",
    question: "Sur Fedora/Red Hat, les fichiers .conf places dans conf.d/ sont-ils charges automatiquement ?",
    options: [
      "Non, il faut les activer avec a2ensite",
      "Oui, Apache les charge automatiquement au demarrage",
      "Non, il faut les inclure manuellement dans httpd.conf",
      "Oui, mais seulement apres un redemarrage complet",
    ],
    correct: 1,
    explanation: "Sur Fedora/Red Hat, tous les fichiers .conf dans /etc/httpd/conf.d/ sont inclus automatiquement. Il n'y a pas de commande a2ensite — il suffit de placer le fichier et de recharger Apache.",
  },
  {
    id: 37,
    type: "qcm",
    question: "Quelle directive configure le fichier journal des erreurs dans un VirtualHost ?",
    options: [
      "LogError",
      "CustomLog",
      "ErrorLog",
      "AccessLog",
    ],
    correct: 2,
    explanation: "La directive ErrorLog definit le chemin du fichier journal des erreurs pour ce VirtualHost. CustomLog configure le journal des acces avec un format specifique.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Que se passe-t-il si deux VirtualHosts ont le meme ServerName sur le meme port ?",
    options: [
      "Apache refuse de demarrer et signale une erreur",
      "Apache utilise le premier VirtualHost defini dans la configuration",
      "Apache utilise le dernier VirtualHost defini dans la configuration",
      "Apache distribue les requetes entre les deux VirtualHosts",
    ],
    correct: 1,
    explanation: "En cas de conflit, Apache utilise le premier VirtualHost defini correspondant. C'est pourquoi il est important de donner des noms uniques a chaque site.",
  },
  {
    id: 39,
    type: "qcm",
    question: "Quelle commande verifie la syntaxe d'une zone DNS Bind9 ?",
    options: [
      "sudo bind9 --check ofppt.local",
      "sudo named-checkconf ofppt.local",
      "sudo named-checkzone ofppt.local /var/cache/bind/db.ofppt.local",
      "sudo dig @localhost ofppt.local",
    ],
    correct: 2,
    explanation: "La commande 'named-checkzone' verifie la syntaxe d'un fichier de zone DNS. Elle prend en argument le nom de la zone et le chemin du fichier de zone.",
  },
  {
    id: 40,
    type: "qcm",
    question: "Que signifie le code HTTP 503 ?",
    options: [
      "Authentification requise",
      "Mauvaise reponse du serveur en amont",
      "Serveur temporairement indisponible",
      "Erreur interne du serveur",
    ],
    correct: 2,
    explanation: "Le code 503 (Service Unavailable) indique que le serveur est temporairement incapable de traiter la requete, generalement a cause d'une surcharge ou d'une maintenance en cours.",
  },
];

export default function QuizzApache() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — Serveur Web Apache"
      courseLink="/docs/linux/lesson-07"
    />
  );
}