import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  // ─── Section 1 : Vrai / Faux (10 questions) ───────────────────────────────

  {
    id: 1,
    type: "vf",
    question: "LVM signifie Logical Volume Manager ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. LVM (Logical Volume Manager) est un outil de gestion de volumes logiques integre au noyau Linux.",
  },
  {
    id: 2,
    type: "vf",
    question: "L'ordre correct de creation LVM est : VG → PV → LV ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. L'ordre obligatoire est PV → VG → LV. On initialise d'abord les disques physiques (PV), puis on cree le groupe (VG), puis le volume logique (LV).",
  },
  {
    id: 3,
    type: "vf",
    question: "La commande 'pvcreate' initialise un disque physique pour LVM ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. pvcreate marque un disque ou une partition comme Physical Volume, ce qui est la premiere etape obligatoire avant de l'integrer a un VG.",
  },
  {
    id: 4,
    type: "vf",
    question: "Il est possible d'etendre un volume logique XFS sans le demonter ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. XFS supporte l'extension a chaud avec xfs_growfs. C'est l'un des grands avantages de LVM en production.",
  },
  {
    id: 5,
    type: "vf",
    question: "XFS supporte la reduction d'un volume logique ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. XFS ne supporte que l'extension, jamais la reduction. Pour reduire, il faut sauvegarder les donnees, supprimer le volume et le recreer.",
  },
  {
    id: 6,
    type: "vf",
    question: "La commande 'vgextend' permet d'ajouter un nouveau PV a un VG existant ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. vgextend NomVG /dev/sdX ajoute le volume physique /dev/sdX au groupe de volumes NomVG, augmentant ainsi l'espace disponible.",
  },
  {
    id: 7,
    type: "vf",
    question: "Pour reduire un volume ext4, il faut executer resize2fs APRES lvreduce ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. L'ordre obligatoire est resize2fs AVANT lvreduce. Inverser cet ordre detruit les donnees car le systeme de fichiers serait tronque.",
  },
  {
    id: 8,
    type: "vf",
    question: "Un snapshot LVM copie immediatement toutes les donnees du volume source ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Un snapshot utilise le principe Copy-on-Write : il enregistre uniquement les blocs modifies apres sa creation, pas toutes les donnees.",
  },
  {
    id: 9,
    type: "vf",
    question: "La commande 'lvs' affiche la liste courte des volumes logiques ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. 'lvs' affiche un resume compact des LV. 'lvdisplay' affiche les details complets et 'lvscan' scanne tous les LV du systeme.",
  },
  {
    id: 10,
    type: "vf",
    question: "L'ordre de suppression LVM est : pvremove → vgremove → lvremove ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. L'ordre obligatoire de suppression est : umount → lvremove → vgremove → pvremove. On supprime du plus haut niveau vers le plus bas.",
  },

  // ─── Section 2 : QCM (30 questions) ───────────────────────────────────────

  {
    id: 11,
    type: "qcm",
    question: "Quelle est la commande pour installer LVM sur Ubuntu ?",
    options: [
      "sudo dnf install lvm2 -y",
      "sudo apt install lvm -y",
      "sudo apt install lvm2 -y",
      "sudo apt install logical-volume -y",
    ],
    correct: 2,
    explanation: "Sur Ubuntu/Debian, le paquet s'appelle 'lvm2' et s'installe avec apt. Sur Fedora/Red Hat, la commande est 'sudo dnf install lvm2 -y'.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Quelle commande initialise le disque /dev/sdb comme Physical Volume ?",
    options: [
      "sudo vgcreate /dev/sdb",
      "sudo lvcreate /dev/sdb",
      "sudo pvmake /dev/sdb",
      "sudo pvcreate /dev/sdb",
    ],
    correct: 3,
    explanation: "pvcreate est la commande qui marque un disque comme Physical Volume LVM. C'est toujours la premiere etape de la creation LVM.",
  },
  {
    id: 13,
    type: "qcm",
    question: "Quelle commande cree un Volume Group nomme 'vgdata' avec les disques /dev/sdb et /dev/sdc ?",
    options: [
      "sudo vgcreate vgdata /dev/sdb /dev/sdc",
      "sudo vgmake vgdata /dev/sdb /dev/sdc",
      "sudo vgcreate /dev/sdb /dev/sdc vgdata",
      "sudo lvcreate vgdata /dev/sdb /dev/sdc",
    ],
    correct: 0,
    explanation: "La syntaxe correcte est : vgcreate NomVG PV1 PV2 ... Le nom du VG vient en premier, suivi des volumes physiques.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Quelle commande cree un volume logique de 50G nomme 'lvweb' dans le VG 'vgdata' ?",
    options: [
      "sudo lvcreate -S 50G -n lvweb vgdata",
      "sudo lvcreate -L 50G -n lvweb vgdata",
      "sudo lvcreate -l 50G -n lvweb vgdata",
      "sudo lvmake -L 50G lvweb vgdata",
    ],
    correct: 1,
    explanation: "L'option -L (majuscule) definit la taille absolue (50G). L'option -l (minuscule) definit la taille en extents ou en pourcentage. -n definit le nom du LV.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Quelle commande cree un LV qui utilise tout l'espace disponible du VG ?",
    options: [
      "sudo lvcreate -L 100% -n NomLV NomVG",
      "sudo lvcreate -l 100%VG -n NomLV NomVG",
      "sudo lvcreate -l 100%FREE -n NomLV NomVG",
      "sudo lvcreate --all -n NomLV NomVG",
    ],
    correct: 2,
    explanation: "L'option '-l 100%FREE' utilise tout l'espace libre du VG. '100%VG' utiliserait tout l'espace total du VG, ce qui provoquerait une erreur si de l'espace est deja utilise.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Quelle commande formate le volume /dev/vgdata/lvweb en ext4 ?",
    options: [
      "sudo format /dev/vgdata/lvweb ext4",
      "sudo mkfs /dev/vgdata/lvweb -t ext4",
      "sudo mkfs.ext4 /dev/vgdata/lvweb",
      "sudo mke2fs /dev/vgdata/lvweb",
    ],
    correct: 2,
    explanation: "mkfs.ext4 est la commande standard pour formater en ext4. On peut aussi utiliser 'mkfs -t ext4', mais mkfs.ext4 est plus explicite et recommandee.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Quel fichier doit etre modifie pour rendre un montage LVM permanent apres redemarrage ?",
    options: [
      "/etc/lvm/lvm.conf",
      "/etc/mount.conf",
      "/etc/fstab",
      "/etc/volumes",
    ],
    correct: 2,
    explanation: "Le fichier /etc/fstab contient les montages permanents du systeme. Sans entree dans ce fichier, le volume ne sera pas monte automatiquement au demarrage.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Quelle commande affiche les details complets d'un Volume Group ?",
    options: [
      "sudo vgs",
      "sudo vginfo",
      "sudo vgdisplay",
      "sudo vgshow",
    ],
    correct: 2,
    explanation: "vgdisplay affiche les details complets : taille totale, espace libre, nombre de PV et LV. vgs affiche une liste courte et resumee.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Quelle commande etend le LV /dev/vgdata/lvweb de 20G supplementaires ?",
    options: [
      "sudo lvgrow -L +20G /dev/vgdata/lvweb",
      "sudo lvextend -L +20G /dev/vgdata/lvweb",
      "sudo lvresize +20G /dev/vgdata/lvweb",
      "sudo lvadd -L 20G /dev/vgdata/lvweb",
    ],
    correct: 1,
    explanation: "lvextend avec l'option -L +20G ajoute 20G a la taille actuelle. Sans le '+', la commande fixerait la taille totale a 20G au lieu d'en ajouter.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Apres avoir etendu un LV ext4, quelle commande etend le systeme de fichiers ?",
    options: [
      "sudo fsck /dev/vgdata/lvweb",
      "sudo e2fsck -f /dev/vgdata/lvweb",
      "sudo xfs_growfs /mnt/data",
      "sudo resize2fs /dev/vgdata/lvweb",
    ],
    correct: 3,
    explanation: "resize2fs redimensionne le systeme de fichiers ext4 pour occuper tout l'espace du LV. Cette commande peut s'executer a chaud, sans demonter le volume.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Quelle commande etend le systeme de fichiers XFS apres extension du LV ?",
    options: [
      "sudo resize2fs /dev/vgdata/lvweb",
      "sudo xfs_resize /mnt/data",
      "sudo xfs_growfs /mnt/data",
      "sudo fsadm resize /dev/vgdata/lvweb",
    ],
    correct: 2,
    explanation: "xfs_growfs prend en argument le point de montage (pas le chemin du device). Il etend le systeme de fichiers XFS pour occuper tout l'espace disponible du LV.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Avant de reduire un volume ext4, quelle commande verifie l'integrite du systeme de fichiers ?",
    options: [
      "sudo fsck /dev/vgdata/lvweb",
      "sudo e2fsck -f /dev/vgdata/lvweb",
      "sudo xfs_check /dev/vgdata/lvweb",
      "sudo lvcheck /dev/vgdata/lvweb",
    ],
    correct: 1,
    explanation: "e2fsck -f force la verification du systeme de fichiers ext4, meme s'il semble propre. Cette etape est obligatoire avant toute reduction pour eviter la corruption des donnees.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Quel est l'ordre correct pour reduire un volume logique ext4 de 50G a 30G ?",
    options: [
      "lvreduce → resize2fs → umount → e2fsck → mount",
      "umount → lvreduce → resize2fs → e2fsck → mount",
      "umount → e2fsck → resize2fs → lvreduce → mount",
      "umount → resize2fs → e2fsck → lvreduce → mount",
    ],
    correct: 2,
    explanation: "L'ordre obligatoire est : umount (demonter) → e2fsck (verifier) → resize2fs (reduire le FS) → lvreduce (reduire le LV) → mount (remonter). resize2fs doit toujours preceder lvreduce.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Quelle commande cree un snapshot de 10G du LV /dev/vgdata/lvweb ?",
    options: [
      "sudo lvcreate --backup 10G --name snap1 /dev/vgdata/lvweb",
      "sudo lvcreate --size 10G --snapshot --name snap1 /dev/vgdata/lvweb",
      "sudo lvsnap -s 10G /dev/vgdata/lvweb snap1",
      "sudo snapshot -L 10G /dev/vgdata/lvweb snap1",
    ],
    correct: 1,
    explanation: "La syntaxe correcte utilise --snapshot (ou -s) pour indiquer que c'est un snapshot, --size (ou -L) pour la taille du snapshot, et --name (ou -n) pour son nom.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Quelle commande restaure un snapshot LVM nomme snap1 ?",
    options: [
      "sudo lvrestore /dev/vgdata/snap1",
      "sudo lvconvert --merge /dev/vgdata/snap1",
      "sudo lvreset --snap /dev/vgdata/snap1",
      "sudo snapshot --restore /dev/vgdata/snap1",
    ],
    correct: 1,
    explanation: "lvconvert --merge fusionne le snapshot avec le volume source, restaurant ainsi l'etat du volume au moment de la creation du snapshot. Le LV doit etre demonte avant cette operation.",
  },
  {
    id: 26,
    type: "qcm",
    question: "Quelle commande supprime le volume logique /dev/vgdata/lvweb ?",
    options: [
      "sudo lvrm /dev/vgdata/lvweb",
      "sudo lvdelete /dev/vgdata/lvweb",
      "sudo lvremove /dev/vgdata/lvweb",
      "sudo rm /dev/vgdata/lvweb",
    ],
    correct: 2,
    explanation: "lvremove supprime un volume logique. La commande demande une confirmation avant suppression. Le volume doit etre demonte avant d'etre supprime.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Quelle commande supprime le Volume Group 'vgdata' ?",
    options: [
      "sudo vgremove vgdata",
      "sudo vgdelete vgdata",
      "sudo vgrm vgdata",
      "sudo vgdestroy vgdata",
    ],
    correct: 0,
    explanation: "vgremove supprime un Volume Group. Tous les LV du VG doivent etre supprimes avant de pouvoir supprimer le VG.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Quelle commande retire le disque /dev/sdc d'un VG existant ?",
    options: [
      "sudo vgremove vgdata /dev/sdc",
      "sudo pvremove vgdata /dev/sdc",
      "sudo vgreduce vgdata /dev/sdc",
      "sudo vgdetach vgdata /dev/sdc",
    ],
    correct: 2,
    explanation: "vgreduce retire un PV d'un VG. Attention, le PV doit etre vide (ne contenir aucune donnee LVM) avant de pouvoir etre retire. Utilisez pvmove d'abord si necessaire.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Quel fichier contient la configuration globale de LVM ?",
    options: [
      "/etc/lvm/volumes.conf",
      "/etc/lvm/lvm.conf",
      "/etc/lvm2/config",
      "/var/lvm/lvm.conf",
    ],
    correct: 1,
    explanation: "Le fichier /etc/lvm/lvm.conf contient la configuration globale de LVM : filtres de disques, parametres de cache, comportement des metadonnees, etc.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Que signifie l'option '-l 100%FREE' dans la commande lvcreate ?",
    options: [
      "Utiliser 100% de la taille du premier PV",
      "Utiliser tout l'espace libre disponible dans le VG",
      "Creer un LV de 100 extents",
      "Utiliser 100% de la RAM disponible",
    ],
    correct: 1,
    explanation: "100%FREE signifie utiliser tout l'espace libre (non alloue) dans le VG. C'est utile quand on veut creer un seul LV qui occupe tout l'espace disponible.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Quelle est la difference entre 'pvs' et 'pvdisplay' ?",
    options: [
      "pvs affiche les VG, pvdisplay affiche les PV",
      "pvs affiche une liste courte, pvdisplay affiche les details complets",
      "pvs est pour Ubuntu, pvdisplay est pour Fedora",
      "pvs verifie les PV, pvdisplay les repare",
    ],
    correct: 1,
    explanation: "pvs affiche une liste courte et tabulaire des PV (nom, VG, taille). pvdisplay affiche tous les details d'un PV : UUID, taille en PE, espace alloue, etc.",
  },
  {
    id: 32,
    type: "qcm",
    question: "Quelle commande scanne et affiche tous les volumes logiques du systeme ?",
    options: [
      "sudo lvlist",
      "sudo lvs --all",
      "sudo lvscan",
      "sudo lvshow",
    ],
    correct: 2,
    explanation: "lvscan parcourt tous les groupes de volumes et liste les LV avec leur etat (active/inactive) et leur chemin complet.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Sur Fedora, quelle commande formate un LV en XFS ?",
    options: [
      "sudo mkfs.ext4 /dev/NomVG/NomLV",
      "sudo format xfs /dev/NomVG/NomLV",
      "sudo mkfs.xfs /dev/NomVG/NomLV",
      "sudo xfs_mkfs /dev/NomVG/NomLV",
    ],
    correct: 2,
    explanation: "mkfs.xfs formate un volume en XFS. C'est le format par defaut sur Fedora/Red Hat. Sur Ubuntu, ext4 est plus courant et s'installe avec mkfs.ext4.",
  },
  {
    id: 34,
    type: "qcm",
    question: "Pourquoi faut-il demonter un volume avant de le reduire ?",
    options: [
      "Pour liberer de la RAM",
      "Pour eviter la corruption des donnees en cours d'ecriture",
      "Parce que lvreduce refuse de fonctionner sur un volume monte",
      "Pour permettre a e2fsck de fonctionner",
    ],
    correct: 1,
    explanation: "Reduire un volume monte pourrait corrompre les donnees si des ecritures sont en cours. e2fsck et resize2fs necessitent aussi que le volume soit demonte pour fonctionner correctement.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Quelle entree fstab est correcte pour monter /dev/vgdata/lvweb sur /mnt/web en ext4 ?",
    options: [
      "/mnt/web /dev/vgdata/lvweb ext4 defaults 0 2",
      "/dev/vgdata/lvweb /mnt/web ext4 defaults 0 2",
      "/dev/vgdata/lvweb /mnt/web defaults ext4 0 2",
      "lvm /dev/vgdata/lvweb /mnt/web ext4 0 2",
    ],
    correct: 1,
    explanation: "La syntaxe fstab est : DEVICE POINT_DE_MONTAGE TYPE_FS OPTIONS DUMP PASS. Le device vient en premier, puis le point de montage, puis le type de systeme de fichiers.",
  },
  {
    id: 36,
    type: "qcm",
    question: "Comment fonctionne le mecanisme Copy-on-Write d'un snapshot LVM ?",
    options: [
      "Il copie toutes les donnees immediatement lors de la creation",
      "Il copie uniquement les blocs modifies apres la creation du snapshot",
      "Il copie les donnees en arriere-plan pendant les heures creuses",
      "Il compresse les donnees avant de les copier",
    ],
    correct: 1,
    explanation: "Le Copy-on-Write (CoW) enregistre uniquement les blocs qui sont modifies apres la creation du snapshot. Cela rend la creation instantanee et economise l'espace disque.",
  },
  {
    id: 37,
    type: "qcm",
    question: "Quelle commande ajoute le PV /dev/sde au VG 'vgdata' existant ?",
    options: [
      "sudo vgadd vgdata /dev/sde",
      "sudo vgextend vgdata /dev/sde",
      "sudo pvextend vgdata /dev/sde",
      "sudo vginsert /dev/sde vgdata",
    ],
    correct: 1,
    explanation: "vgextend ajoute un PV a un VG existant. Le PV doit etre initialise avec pvcreate avant de pouvoir etre ajoute. Apres cette operation, l'espace du VG augmente.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Quelle commande affiche la liste courte de tous les Volume Groups ?",
    options: [
      "sudo vglist",
      "sudo vgshow",
      "sudo vgs",
      "sudo vgdisplay --short",
    ],
    correct: 2,
    explanation: "vgs affiche une liste tabulaire et resumee de tous les VG : nom, nombre de PV, nombre de LV, taille totale et espace libre.",
  },
  {
    id: 39,
    type: "qcm",
    question: "Quelle est la commande pour supprimer le PV /dev/sdb apres avoir supprime le VG ?",
    options: [
      "sudo pvdelete /dev/sdb",
      "sudo pvremove /dev/sdb",
      "sudo pvrm /dev/sdb",
      "sudo pvcreate --remove /dev/sdb",
    ],
    correct: 1,
    explanation: "pvremove supprime les metadonnees LVM d'un disque, le rendant a nouveau disponible comme disque ordinaire. Le disque doit avoir ete retire du VG avant cette operation.",
  },
  {
    id: 40,
    type: "qcm",
    question: "Quel est l'avantage principal de LVM par rapport au partitionnement classique ?",
    options: [
      "LVM est plus rapide que le partitionnement classique",
      "LVM chiffre automatiquement les donnees",
      "LVM permet de redimensionner les volumes sans redemarrage ni perte de donnees",
      "LVM consomme moins d'espace disque",
    ],
    correct: 2,
    explanation: "L'avantage principal de LVM est la flexibilite : on peut etendre ou reorganiser les volumes a chaud, sans interrompre le service ni perdre de donnees — impossible avec le partitionnement classique.",
  },
];

export default function QuizzLVM() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — LVM Gestion des Volumes Logiques"
      courseLink="/docs/linux/lesson-04"
    />
  );
}