import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  // ===== Commandes de base (existantes) =====
  {
    id: 1,
    type: "qcm",
    question: "Quelle commande affiche la version du noyau Linux actuellement démarré ?",
    options: ["kernel --version", "uname -r", "lsmod -v", "dmesg --version"],
    correct: 1,
    explanation: "`uname -r` affiche la version du noyau actuellement actif.",
  },
  {
    id: 2,
    type: "qcm",
    question: "Quelle commande liste les modules du noyau actuellement chargés ?",
    options: ["modinfo", "modprobe", "lsmod", "sysctl"],
    correct: 2,
    explanation: "`lsmod` affiche la liste des modules chargés. `modinfo` affiche les informations sur un module précis.",
  },
  {
    id: 3,
    type: "qcm",
    question: "Quelle commande consulte les messages du noyau dans le journal systemd ?",
    options: ["journalctl -k", "systemctl kernel", "journalctl -u kernel", "dmesg -s"],
    correct: 0,
    explanation: "`journalctl -k` affiche les messages du noyau enregistrés depuis le démarrage.",
  },

  // ===== Versions du noyau =====
  {
    id: 4,
    type: "qcm",
    question: "Dans l'ancien modèle de numérotation (avant 2.6), que signifie la version 2.5 ?",
    options: ["Version stable", "Version de développement", "Version majeure", "Version corrigée de 2.4"],
    correct: 1,
    explanation: "Avant 2.6, un numéro mineur impair (2.3, 2.5) désigne une version de développement ; un numéro pair (2.2, 2.4) une version stable.",
  },
  {
    id: 5,
    type: "qcm",
    question: "Depuis la version 2.6, que signifie un numéro mineur pair ou impair ?",
    options: [
      "Pair = stable, impair = développement",
      "Pair = développement, impair = stable",
      "Rien de particulier : la règle est abandonnée",
      "Pair = 32 bits, impair = 64 bits",
    ],
    correct: 2,
    explanation: "Le modèle stable/développement basé sur la parité a été abandonné à partir de la 2.6.",
  },
  {
    id: 6,
    type: "qcm",
    question: "Quels changements ont fait passer le noyau de la version majeure 1 à 2 ?",
    options: [
      "Un correctif de sécurité",
      "Un nouveau pilote réseau",
      "Un changement majeur dans le code et le concept du noyau (1996)",
      "Une simple recompilation",
    ],
    correct: 2,
    explanation: "Le numéro majeur ne change que pour de gros changements : 1.0 en 1994, 2.0 en 1996.",
  },
  {
    id: 7,
    type: "qcm",
    question: "Dans le modèle moderne, que représente `6.6.3` ?",
    options: [
      "La 3e version de développement de 6.6",
      "La base 6.6 avec 3 séries de correctifs stable",
      "La version 6.6 pour la 3e architecture",
      "La version majeure 6, mineure 6, build 3 du compilateur",
    ],
    correct: 1,
    explanation: "`6.6` est la base ; le 3e chiffre compte les versions stable (bugs et sécurité, sans nouveauté).",
  },
  {
    id: 8,
    type: "qcm",
    question: "Que contient une version stable (par exemple 6.6.3) par rapport à la base 6.6 ?",
    options: [
      "De nouvelles fonctionnalités majeures",
      "Uniquement des corrections de bugs et de sécurité",
      "Un nouveau compilateur",
      "Un changement d'architecture",
    ],
    correct: 1,
    explanation: "Une version stable est une base corrigée : on n'y ajoute aucune nouveauté.",
  },

  // ===== Patchs : définitions =====
  {
    id: 9,
    type: "qcm",
    question: "Qu'est-ce qu'un patch ?",
    options: [
      "Un noyau complet compressé",
      "Un fichier décrivant les différences entre deux versions de fichiers",
      "Un module du noyau",
      "Un fichier de configuration GRUB",
    ],
    correct: 1,
    explanation: "Un patch est un fichier texte de différences (créé avec `diff`) qu'on applique avec la commande `patch`.",
  },
  {
    id: 10,
    type: "qcm",
    question: "Que signifie l'option `-p1` dans `patch -p1 < fichier` ?",
    options: [
      "Applique le patch une seule fois",
      "Retire le premier niveau de dossier dans les chemins du patch",
      "Passe en mode pause",
      "Applique uniquement le premier fichier",
    ],
    correct: 1,
    explanation: "`-p1` supprime le premier niveau de chemin (`a/` et `b/`), car on est déjà dans le dossier des sources.",
  },
  {
    id: 11,
    type: "qcm",
    question: "Quelle commande annule un patch déjà appliqué ?",
    options: ["patch -p1", "patch -R -p1", "unpatch -p1", "make clean"],
    correct: 1,
    explanation: "`-R` (reverse) retire le patch.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Quelle commande teste un patch sans modifier les fichiers ?",
    options: ["patch -p1 --dry-run", "patch -p1 --test-all", "patch -n", "patch --check-only"],
    correct: 0,
    explanation: "`--dry-run` simule l'application : on voit les erreurs éventuelles sans rien modifier.",
  },
  {
    id: 13,
    type: "qcm",
    question: "Dans `patch-6.6.2-3`, le tiret indique :",
    options: [
      "Une soustraction de versions",
      "Un patch incrémental de 6.6.2 vers 6.6.3",
      "Un patch de la base 6.6 vers 6.6.3",
      "Un patch de 6.6 vers 6.7",
    ],
    correct: 1,
    explanation: "Le format `X.y-z` désigne un patch incrémental qui transforme exactement X.y en X.z.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Un fichier `.rej` apparaît après un patch. Qu'est-ce que cela indique ?",
    options: [
      "Le patch a réussi",
      "Le patch n'a pas pu s'appliquer sur certaines parties : l'arbre n'est pas dans l'état attendu",
      "Le noyau est compilé",
      "Le patch est compressé",
    ],
    correct: 1,
    explanation: "Les `.rej` contiennent les morceaux refusés : en général, mauvaise version de départ.",
  },

  // ===== Patchs : quel patch pour quel cas =====
  {
    id: 15,
    type: "qcm",
    question: "Tu as un arbre 6.6 propre. Quel patch donne 6.6.4 ?",
    options: ["patch-6.6.3-4", "patch-6.6.4", "patch-6.7", "patch-6.6-4"],
    correct: 1,
    explanation: "Base → stable : on applique le patch stable cumulatif `patch-6.6.4`.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Que fait `patch-6.6.2-3` ?",
    options: ["6.6 → 6.6.3", "6.6.3 → 6.6.2", "6.6.2 → 6.6.3", "6.6 → 6.7"],
    correct: 2,
    explanation: "L'incrémental `2-3` fait passer de 6.6.2 à 6.6.3, rien d'autre.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Tu es en 6.6.1 et tu appliques `patch-6.6.2-3`. Que se passe-t-il ?",
    options: [
      "Tu passes en 6.6.3",
      "Tu passes en 6.6.2",
      "Échec : fichiers `.rej` ou arbre cassé",
      "Le patch est ignoré silencieusement",
    ],
    correct: 2,
    explanation: "L'incrémental exige d'être exactement en 6.6.2.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Tu es en 6.6.5 et tu veux passer en 6.7. Que fais-tu ?",
    options: [
      "`patch-6.7` directement",
      "`patch-6.6.5-7`",
      "`patch -R` du patch 6.6.5 pour revenir à 6.6, puis `patch-6.7`",
      "`patch-6.6.6` puis `patch-6.7`",
    ],
    correct: 2,
    explanation: "Les patchs de base partent de la base propre : on revient à 6.6 avec `-R`, puis on applique `patch-6.7`.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Tu es en 6.2.4 stable et tu veux 6.2.7 en utilisant uniquement des incrémentaux. Lesquels ?",
    options: [
      "`patch-6.2.4-7`",
      "`patch-6.2.7`",
      "`patch-6.2.4-5`, puis `5-6`, puis `6-7`",
      "`patch-6.2.6-7`, puis `5-6`, puis `4-5`",
    ],
    correct: 2,
    explanation: "On chaîne les incrémentaux dans l'ordre, sans en sauter aucun.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Tu es en 6.5 et tu veux 6.7. Que fais-tu ?",
    options: [
      "`patch-6.7` directement",
      "`patch-6.6`, puis `patch-6.7`",
      "`patch-6.5-7`",
      "`patch-6.6.1`, puis `patch-6.7`",
    ],
    correct: 1,
    explanation: "On ne saute pas de base : 6.5 → 6.6 → 6.7.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Tu es en 6.6.4 et tu veux revenir en 6.6.3. Que fais-tu ?",
    options: [
      "`patch-6.6.3`",
      "`patch-6.6.3-4` sans option",
      "`patch -R` avec `patch-6.6.3-4`",
      "`patch -R` avec `patch-6.6.3`",
    ],
    correct: 2,
    explanation: "Retour arrière = même patch incrémental avec `-R`.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Tu es en 6.6.3 et tu veux 6.7.2. Quelle séquence est correcte ?",
    options: [
      "`patch-6.7.2` directement",
      "`-R patch-6.6.3`, puis `patch-6.7`, puis `patch-6.7.2`",
      "`patch-6.7`, puis `-R patch-6.6.3`, puis `patch-6.7.2`",
      "`patch-6.6.3-7.2`",
    ],
    correct: 1,
    explanation: "Retour à la base 6.6, passage à 6.7, puis application du stable cumulatif 6.7.2.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Un patch stable (cumulatif) comme `patch-2.6.17.10` s'applique sur :",
    options: [
      "Un 2.6.17.9",
      "Un 2.6.17 base propre",
      "Un 2.6.18",
      "N'importe quelle version 2.6",
    ],
    correct: 1,
    explanation: "Un patch stable part toujours de la base (ici 2.6.17), jamais d'un autre stable.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Tu es en 2.6.17.9. Quel est le bon moyen d'arriver en 2.6.17.10 ?",
    options: [
      "Appliquer `patch-2.6.17.10` directement",
      "Appliquer l'incrémental `patch-2.6.17.9-10`",
      "Appliquer `patch-2.6.18`",
      "Réinstaller le système",
    ],
    correct: 1,
    explanation: "L'incrémental `9-10` part exactement de 2.6.17.9. Le cumulatif échouerait sur un arbre déjà stable.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Pourquoi utilise-t-on un patch incrémental plutôt qu'un cumulatif quand on est déjà en stable ?",
    options: [
      "Il est plus petit : il ne contient que la différence entre deux stables consécutifs",
      "Il change de série automatiquement",
      "Il compile le noyau",
      "Il supprime les modules inutiles",
    ],
    correct: 0,
    explanation: "L'incrémental ne contient que le delta, donc il est léger et rapide à télécharger.",
  },

  // ===== Procédure de mise à jour =====
  {
    id: 26,
    type: "qcm",
    question: "Pourquoi mettre à jour un noyau avec des patchs plutôt que tout refaire ?",
    options: [
      "Pour changer d'architecture",
      "Pour garder la personnalisation et la configuration déjà faites",
      "Pour supprimer les modules",
      "Pour éviter d'utiliser un compilateur",
    ],
    correct: 1,
    explanation: "On conserve l'arbre de sources et le `.config` : on ne perd pas le temps de personnalisation et de compilation.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Quel est l'ordre correct des 5 étapes de mise à jour d'un noyau ?",
    options: [
      "Compiler, configurer, patcher, installer, obtenir les sources",
      "Obtenir les sources, appliquer les patchs, reconfigurer, compiler, installer",
      "Installer, compiler, patcher, configurer, obtenir les sources",
      "Configurer, installer, compiler, patcher, obtenir les sources",
    ],
    correct: 1,
    explanation: "Sources → patchs → reconfiguration (`oldconfig`) → compilation (`make`) → installation.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Que fait la commande `make oldconfig` ?",
    options: [
      "Elle supprime l'ancien `.config`",
      "Elle reprend l'ancien `.config` et ne pose des questions que sur les nouvelles options",
      "Elle compile le noyau",
      "Elle installe les modules",
    ],
    correct: 1,
    explanation: "Les réponses déjà données sont conservées ; seules les nouvelles options du noyau sont demandées.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Dans `make oldconfig`, que signifie la réponse `m` ?",
    options: [
      "Option désactivée",
      "Option intégrée dans le noyau",
      "Option compilée en module",
      "Afficher l'aide",
    ],
    correct: 2,
    explanation: "`y` = intégré, `m` = module chargeable, `n` = désactivé, `?` = aide.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Où se trouve le fichier `.config` et pourquoi `ls` ne l'affiche pas ?",
    options: [
      "Dans `/etc`, car il est protégé",
      "À la racine des sources du noyau ; c'est un fichier caché (il commence par un point)",
      "Dans `/boot` uniquement",
      "Il n'existe qu'après le reboot",
    ],
    correct: 1,
    explanation: "Il se trouve dans le dossier des sources (ex. `linux-3.17/.config`). Il faut `ls -a` pour le voir.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Quelle commande copie la configuration du noyau actuel comme point de départ ?",
    options: [
      "`cp /boot/config-$(uname -r) .config`",
      "`cp /etc/config .config`",
      "`mv .config /boot`",
      "`make clean`",
    ],
    correct: 0,
    explanation: "Copier `/boot/config-<version>` évite de répondre à toutes les questions de configuration.",
  },
  {
    id: 32,
    type: "qcm",
    question: "Quelle est la bonne commande pour installer les modules compilés ?",
    options: ["make install_modules", "make modules_install", "make modules", "make install -m"],
    correct: 1,
    explanation: "La cible s'appelle `modules_install`. Elle copie les `.ko` dans `/lib/modules/<version>/` et lance `depmod`.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Quel est le bon ordre d'installation ?",
    options: [
      "`make install` puis `make modules_install`",
      "`make modules_install` puis `make install`",
      "`update-grub2` puis `make`",
      "`make install` puis `make oldconfig`",
    ],
    correct: 1,
    explanation: "Les modules d'abord, pour que l'initramfs créé par `make install` contienne les bons modules.",
  },
  {
    id: 34,
    type: "qcm",
    question: "Que fait `make install` pour le noyau ?",
    options: [
      "Il installe le noyau dans `/boot` (`vmlinuz`, `System.map`, `config`)",
      "Il installe uniquement les modules",
      "Il supprime l'ancien noyau",
      "Il désinstalle GRUB",
    ],
    correct: 0,
    explanation: "`make install` place le noyau et ses fichiers associés dans `/boot` ; `modules_install` s'occupe de `/lib/modules`.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Dans `/boot/grub/`, quel fichier contient le menu de GRUB 2 (Debian) ?",
    options: ["menu.lst", "grub.cfg", "sysctl.conf", "modules.dep"],
    correct: 1,
    explanation: "GRUB 2 utilise `grub.cfg` ; GRUB legacy (Fedora du TP) utilise `menu.lst`.",
  },
  {
    id: 36,
    type: "qcm",
    question: "Sur Fedora (GRUB legacy) du TP, quel fichier édite-t-on pour modifier le timeout de démarrage ?",
    options: ["/boot/grub/grub.cfg", "/boot/grub/menu.lst", "/etc/modprobe.conf", "/etc/fstab"],
    correct: 1,
    explanation: "Avec GRUB legacy, le menu et le timeout se règlent dans `/boot/grub/menu.lst`.",
  },
  {
    id: 37,
    type: "qcm",
    question: "Sur Debian, à quoi sert `update-grub2` ?",
    options: [
      "À compiler le noyau",
      "À régénérer `grub.cfg` en détectant les noyaux présents dans `/boot`",
      "À appliquer un patch",
      "À charger un module",
    ],
    correct: 1,
    explanation: "Il scanne `/boot` et ajoute une entrée de menu pour chaque noyau installé.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Dans le TP, pourquoi compte-t-on les lignes de `grub.cfg` avec `wc -l` avant et après `update-grub2` ?",
    options: [
      "Pour compresser le fichier",
      "Pour vérifier que le fichier a bien été modifié (nouvelles entrées ajoutées)",
      "Pour supprimer les lignes vides",
      "Pour changer le timeout",
    ],
    correct: 1,
    explanation: "Un nombre de lignes plus grand après la commande indique que de nouvelles entrées de menu ont été ajoutées.",
  },
  {
    id: 39,
    type: "qcm",
    question: "Sur Debian, le système affiche un kernel panic au démarrage car l'initrd est introuvable. Que faire ?",
    options: [
      "`make clean`",
      "`mkinitramfs -o /boot/initrd.img-3.18.5 /lib/modules/3.18.5/` puis `update-grub2`",
      "`patch -R -p1`",
      "`rmmod` de tous les modules",
    ],
    correct: 1,
    explanation: "On crée l'image initrd manquante avec `mkinitramfs`, puis on régénère le menu GRUB.",
  },
  {
    id: 40,
    type: "qcm",
    question: "Quelle commande affiche rapidement la version des sources du noyau patché ?",
    options: ["uname -r", "head Makefile", "lsmod", "cat /proc/modules"],
    correct: 1,
    explanation: "`head Makefile` montre `VERSION`, `PATCHLEVEL` et `SUBLEVEL` des sources. `uname -r` montre le noyau en cours d'exécution, pas les sources.",
  },
  {
    id: 41,
    type: "qcm",
    question: "Après `patch-3.18` puis `patch-3.18.2` (cumulatif) sur 3.17, pourquoi le second patch fonctionne-t-il ?",
    options: [
      "Parce que l'arbre est en 3.18 propre, qui est la base attendue par le patch stable 3.18.2",
      "Parce que le patch est incrémental",
      "Parce que `-p1` change la version de départ",
      "Parce que `make` corrige automatiquement",
    ],
    correct: 0,
    explanation: "Après `patch-3.18`, l'arbre est en base 3.18 propre : c'est exactement ce que le stable cumulatif 3.18.2 attend.",
  },
  {
    id: 42,
    type: "qcm",
    question: "Après les patchs, le dossier s'appelle toujours `linux-3.17`. Que contient-il ?",
    options: [
      "Les sources 3.17 d'origine",
      "Les sources en version 3.18.5",
      "Un noyau vide",
      "Uniquement les modules",
    ],
    correct: 1,
    explanation: "Le nom du dossier ne change pas, mais son contenu est en 3.18.5 : on peut le renommer si on veut.",
  },
  {
    id: 43,
    type: "qcm",
    question: "Dans l'historique du TP, `gunzip patch-*.rpm` est :",
    options: [
      "Une étape obligatoire",
      "Une erreur : un `.rpm` n'est pas un fichier gzip",
      "La commande pour installer l'outil patch",
      "La commande pour appliquer le patch",
    ],
    correct: 1,
    explanation: "Seul `gunzip patch-*.gz` décompresse les patchs. Un `.rpm` s'installe avec `rpm -ivh`.",
  },
  {
    id: 44,
    type: "qcm",
    question: "Quelle commande installe un paquet `.deb` sur Debian ?",
    options: ["rpm -ivh", "dpkg -i", "dkpg -ivh", "gunzip"],
    correct: 1,
    explanation: "`dpkg -i paquet.deb` (et non `dkpg`). `rpm -ivh` est pour Fedora/Red Hat.",
  },

  // ===== Paramètres dynamiques /proc/sys =====
  {
    id: 45,
    type: "qcm",
    question: "Où se trouvent les paramètres du noyau modifiables dynamiquement ?",
    options: ["/boot", "/proc/sys", "/usr/src", "/lib/modules"],
    correct: 1,
    explanation: "Les paramètres sont exposés sous forme de fichiers dans `/proc/sys`.",
  },
  {
    id: 46,
    type: "qcm",
    question: "Quelle commande active le relayage (forwarding) entre cartes réseau immédiatement ?",
    options: [
      "sysctl -p ip_forward",
      "sysctl -w net.ipv4.ip_forward=1",
      "cat 1 > ip_forward",
      "echo 1 > /etc/sysctl.conf",
    ],
    correct: 1,
    explanation: "`sysctl -w variable=valeur` applique tout de suite. `echo 1 > /proc/sys/net/ipv4/ip_forward` marche aussi.",
  },
  {
    id: 47,
    type: "qcm",
    question: "À quoi sert `/proc/sys/net/ipv4/ip_forward` mis à 1 ?",
    options: [
      "Bloquer les pings",
      "Permettre à la machine de fonctionner comme un routeur",
      "Changer le nom de la machine",
      "Limiter le nombre de fichiers ouverts",
    ],
    correct: 1,
    explanation: "Le relayage entre cartes réseau est nécessaire pour faire fonctionner le système comme un routeur.",
  },
  {
    id: 48,
    type: "qcm",
    question: "Quel fichier bloque les réponses au ping ?",
    options: [
      "icmp_echo_ignore_broadcasts",
      "ip_forward",
      "icmp_echo_ignore_all",
      "file-max",
    ],
    correct: 2,
    explanation: "`icmp_echo_ignore_all=1` bloque tous les pings ; `ignore_broadcasts` ne bloque que ceux envoyés en diffusion.",
  },
  {
    id: 49,
    type: "qcm",
    question: "Que contrôle `/proc/sys/fs/file-max` ?",
    options: [
      "La taille maximale d'un fichier",
      "Le nombre maximal de fichiers que le noyau peut manipuler simultanément",
      "Le nombre de modules chargés",
      "Le nombre de processus root",
    ],
    correct: 1,
    explanation: "C'est la limite globale du nombre de fichiers ouverts en même temps.",
  },
  {
    id: 50,
    type: "qcm",
    question: "Quel fichier permet de changer le nom de la machine à chaud ?",
    options: [
      "/proc/sys/kernel/hostname",
      "/proc/sys/fs/file-max",
      "/proc/sys/net/ipv4/ip_forward",
      "/proc/sys/kernel/ctrl-alt-del",
    ],
    correct: 0,
    explanation: "`/proc/sys/kernel/hostname` contient le nom de la machine.",
  },
  {
    id: 51,
    type: "qcm",
    question: "Si `/proc/sys/kernel/ctrl-alt-del` vaut 0, que se passe-t-il à Ctrl+Alt+Suppr ?",
    options: [
      "Le système s'éteint brutalement",
      "La séquence est capturée et envoyée à `init`, qui relance le système proprement",
      "Rien du tout",
      "Un module est déchargé",
    ],
    correct: 1,
    explanation: "À 0, la séquence est envoyée à `init` pour un redémarrage propre.",
  },
  {
    id: 52,
    type: "qcm",
    question: "Après `echo 1 > /proc/sys/net/ipv4/ip_forward` puis un redémarrage, la valeur est :",
    options: [
      "Toujours 1",
      "Revenue à la valeur définie au démarrage",
      "Effacée définitivement",
      "Copiée dans `/etc/sysctl.conf`",
    ],
    correct: 1,
    explanation: "Sans écriture dans `/etc/sysctl.conf`, le changement est perdu au redémarrage.",
  },
  {
    id: 53,
    type: "qcm",
    question: "Comment rendre le forwarding permanent ?",
    options: [
      "Écrire `net.ipv4.ip_forward = 1` dans `/etc/sysctl.conf`",
      "Écrire `1` dans `/boot/grub/menu.lst`",
      "Lancer `lsmod`",
      "Utiliser `rmmod ip_forward`",
    ],
    correct: 0,
    explanation: "`/etc/sysctl.conf` est lu au démarrage pour définir les valeurs initiales des paramètres.",
  },
  {
    id: 54,
    type: "qcm",
    question: "Quelle commande recharge `/etc/sysctl.conf` sans redémarrer ?",
    options: ["sysctl -w", "sysctl -p", "sysctl -r", "modprobe -p"],
    correct: 1,
    explanation: "`sysctl -p` relit le fichier de configuration et applique ses valeurs immédiatement.",
  },
  {
    id: 55,
    type: "qcm",
    question: "Quelle est la variable `sysctl` équivalente à `/proc/sys/net/ipv4/ip_forward` ?",
    options: [
      "proc.sys.net.ipv4.ip_forward",
      "net.ipv4.ip_forward",
      "ipv4/net/ip_forward",
      "sys.ip_forward",
    ],
    correct: 1,
    explanation: "On enlève `/proc/sys/` et on remplace `/` par `.`.",
  },
  {
    id: 56,
    type: "qcm",
    question: "Quelle différence entre `>` et `>>` dans `echo ... >> /etc/sysctl.conf` ?",
    options: [
      "Aucune",
      "`>>` ajoute à la fin du fichier, `>` écrase tout son contenu",
      "`>>` écrase, `>` ajoute",
      "`>>` supprime la ligne",
    ],
    correct: 1,
    explanation: "Avec `>` le fichier est remplacé ; avec `>>` la ligne est ajoutée à la fin.",
  },

  // ===== Modules =====
  {
    id: 57,
    type: "qcm",
    question: "Où se trouvent les modules du noyau ?",
    options: [
      "/lib/modules/<version>/kernel/drivers",
      "/proc/sys",
      "/boot/grub",
      "/usr/src/linux/.config",
    ],
    correct: 0,
    explanation: "Les modules (`.ko`) sont installés sous `/lib/modules/<version>/`.",
  },
  {
    id: 58,
    type: "qcm",
    question: "Quelle commande donne des informations sur le module `msdos` ?",
    options: ["lsmod msdos", "modinfo msdos", "rmmod msdos", "depmod msdos"],
    correct: 1,
    explanation: "`modinfo` affiche description, auteur, dépendances et paramètres d'un module.",
  },
  {
    id: 59,
    type: "qcm",
    question: "Quelle commande charge un module avec ses dépendances ?",
    options: ["insmod", "modprobe", "rmmod", "lsmod"],
    correct: 1,
    explanation: "`modprobe` lit `modules.dep` et charge automatiquement les modules nécessaires.",
  },
  {
    id: 60,
    type: "qcm",
    question: "Quelle différence entre `insmod` et `modprobe` ?",
    options: [
      "Aucune",
      "`insmod` n'est pas capable de gérer les dépendances ; `modprobe` les gère",
      "`modprobe` est réservé aux modules réseau",
      "`insmod` supprime un module",
    ],
    correct: 1,
    explanation: "`insmod` insère un module précis sans gérer ses dépendances ; `modprobe` les résout.",
  },
  {
    id: 61,
    type: "qcm",
    question: "Quelle commande décharge un module et tente aussi de retirer les modules devenus inutiles ?",
    options: ["rmmod module", "modprobe -r module", "insmod -r module", "lsmod -r"],
    correct: 1,
    explanation: "`modprobe -r` (remove) retire le module et les modules liés non utilisés. `rmmod` retire seulement le module demandé.",
  },
  {
    id: 62,
    type: "qcm",
    question: "Quelle commande génère le fichier `modules.dep` ?",
    options: ["modinfo", "depmod", "lsmod", "insmod"],
    correct: 1,
    explanation: "`depmod` calcule les dépendances ; il est lancé automatiquement par `make modules_install`.",
  },
  {
    id: 63,
    type: "qcm",
    question: "Que contient `modules.dep` ?",
    options: [
      "La liste des modules chargés",
      "Les dépendances de chaque module",
      "La configuration de GRUB",
      "Les paramètres de `sysctl`",
    ],
    correct: 1,
    explanation: "Chaque ligne a la forme `module.ko: dependance1.ko dependance2.ko`.",
  },
  {
    id: 64,
    type: "qcm",
    question: "La ligne `kernel/fs/fat/msdos.ko: kernel/fs/fat/fat.ko` signifie :",
    options: [
      "`msdos` dépend de `fat` : `fat` doit être chargé avant",
      "`fat` dépend de `msdos`",
      "`msdos` et `fat` sont incompatibles",
      "`fat` est une copie de `msdos`",
    ],
    correct: 0,
    explanation: "Ce qui est après les deux-points est la dépendance : `modprobe msdos` charge `fat` d'abord.",
  },
  {
    id: 65,
    type: "qcm",
    question: "Que signifie `alias eth0 3c59x` dans `modprobe.conf` ?",
    options: [
      "Supprimer la carte `eth0`",
      "Associer l'interface `eth0` au pilote (module) `3c59x`",
      "Créer une dépendance entre modules",
      "Charger GRUB",
    ],
    correct: 1,
    explanation: "Ce fichier définit des associations module ↔ périphérique.",
  },
  {
    id: 66,
    type: "qcm",
    question: "Quel fichier de configuration des modules correspond aux noyaux 2.6 et plus ?",
    options: ["modules.conf", "modprobe.conf", "sysctl.conf", "grub.cfg"],
    correct: 1,
    explanation: "`modules.conf` appartient au noyau 2.4 ; `modprobe.conf` aux noyaux 2.6 et plus.",
  },
];



export default function QuizzKernel() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz - Noyau Linux"
      courseLink="/cours/linux/lesson-13"
    />
  );
}
