import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  // ── VRAI / FAUX ──
  {
    id: 1,
    type: "vf",
    question: "Le RAID 0 offre une redondance des donnees en cas de panne d'un disque ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Le RAID 0 (striping) n'offre aucune redondance — si un disque tombe en panne, toutes les donnees sont perdues. Il ameliore uniquement les performances.",
  },
  {
    id: 2,
    type: "vf",
    question: "Le RAID 1 necessite au minimum 2 disques pour fonctionner ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Le RAID 1 (mirroring) necessite exactement 2 disques — les donnees sont ecrites en miroir sur les deux disques simultanement.",
  },
  {
    id: 3,
    type: "vf",
    question: "La commande 'cat /proc/mdstat' affiche l'etat en temps reel de tous les arrays RAID actifs ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. /proc/mdstat est le fichier virtuel du noyau Linux qui expose l'etat de tous les arrays RAID geres par mdadm.",
  },
  {
    id: 4,
    type: "vf",
    question: "Un disque Spare participe activement aux lectures et ecritures dans un array RAID 5 ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Un disque Spare (Hot Spare) reste inactif en temps normal. Il n'intervient qu'automatiquement en cas de panne d'un disque actif pour lancer la reconstruction.",
  },
  {
    id: 5,
    type: "vf",
    question: "La commande 'mdadm --zero-superblock /dev/sdb' efface les metadonnees RAID d'un disque ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. --zero-superblock supprime le superbloc RAID d'un disque, le rendant utilisable pour un nouvel array. Cette etape est obligatoire avant de reutiliser un ancien disque RAID.",
  },
  {
    id: 6,
    type: "vf",
    question: "Le RAID 5 peut tolerer la panne simultanee de 2 disques sans perte de donnees ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Le RAID 5 ne tolere qu'une seule panne disque. C'est le RAID 6 (double parite) qui tolere la panne simultanee de 2 disques.",
  },
  {
    id: 7,
    type: "vf",
    question: "La commande 'mdadm --grow' permet d'etendre un array RAID en ajoutant des disques actifs supplementaires ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. 'mdadm --grow /dev/md0 --raid-devices=N' etend le nombre de disques actifs dans l'array. Apres la reconstruction, il faut aussi etendre le systeme de fichiers avec resize2fs ou xfs_growfs.",
  },
  {
    id: 8,
    type: "vf",
    question: "Sauvegarder la configuration dans mdadm.conf est optionnel si on utilise des disques identifies par UUID ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. La sauvegarde dans mdadm.conf est obligatoire sous Fedora et fortement recommandee sous Ubuntu. Sans cette etape, l'array risque de ne pas etre remonte correctement au demarrage.",
  },
  {
    id: 9,
    type: "vf",
    question: "La commande 'resize2fs /dev/md0' permet d'etendre un systeme de fichiers ext4 sans demonter le volume ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. resize2fs peut etendre un systeme de fichiers ext4 a chaud (sans demontage). En revanche, la reduction necessite obligatoirement de demonter le volume au prealable.",
  },
  {
    id: 10,
    type: "vf",
    question: "Le RAID 10 necessite un minimum de 3 disques pour fonctionner ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Le RAID 10 (miroir + stripe) necessite un minimum de 4 disques — au moins 2 paires de disques en miroir dont les donnees sont reparties par striping.",
  },

  // ── QCM ──
  {
    id: 11,
    type: "qcm",
    question: "Quelle commande permet de creer un RAID 5 avec 3 disques /dev/sdb, /dev/sdc et /dev/sdd ?",
    options: [
      "sudo mdadm --create /dev/md0 --level=5 --raid-devices=3 /dev/sdb /dev/sdc /dev/sdd",
      "sudo mdadm --build /dev/md0 --level=5 --devices=3 /dev/sdb /dev/sdc /dev/sdd",
      "sudo mdadm --new /dev/md0 -l5 -n3 /dev/sdb /dev/sdc /dev/sdd",
      "sudo mdadm --assemble /dev/md0 --level=5 /dev/sdb /dev/sdc /dev/sdd",
    ],
    correct: 0,
    explanation: "La syntaxe correcte est 'mdadm --create' avec --level pour le niveau RAID et --raid-devices pour le nombre de disques actifs. L'option courte equivalente est '-l5 -n3'.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Que signifie l'indicateur (S) dans la sortie de 'cat /proc/mdstat' ?",
    options: [
      "Le disque est en cours de synchronisation",
      "Le disque est un spare (disque de reserve)",
      "Le disque est en etat stopped",
      "Le disque a une erreur SMART",
    ],
    correct: 1,
    explanation: "(S) dans /proc/mdstat indique qu'un disque est un Spare — il est branche et pret a intervenir mais n'est pas actif dans l'array. Un disque actif est note sans lettre ou avec [U].",
  },
  {
    id: 13,
    type: "qcm",
    question: "Quelle est l'espace utile d'un RAID 5 compose de 4 disques de 2 To chacun ?",
    options: [
      "2 To",
      "4 To",
      "6 To",
      "8 To",
    ],
    correct: 2,
    explanation: "Pour un RAID 5, l'espace utile est (N-1) x taille d'un disque. Avec 4 disques de 2 To : (4-1) x 2 To = 6 To. Un disque equivalent est utilise pour la parite repartie.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Quelle commande permet d'ajouter un disque /dev/sde a un array RAID existant /dev/md0 ?",
    options: [
      "sudo mdadm --manage /dev/md0 --insert /dev/sde",
      "sudo mdadm --manage /dev/md0 --add /dev/sde",
      "sudo mdadm --grow /dev/md0 --add /dev/sde",
      "sudo mdadm /dev/md0 --append /dev/sde",
    ],
    correct: 1,
    explanation: "La commande correcte est 'mdadm --manage /dev/md0 --add /dev/sde'. Le disque sera ajoute comme spare si tous les slots actifs sont occupes, ou comme disque actif si un slot est libre.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Quelle est la bonne sequence pour sauvegarder la configuration RAID sous Ubuntu ?",
    options: [
      "sudo mdadm --detail --scan | sudo tee -a /etc/mdadm/mdadm.conf puis sudo update-initramfs -u",
      "sudo mdadm --save /etc/mdadm/mdadm.conf puis sudo systemctl restart mdmonitor",
      "sudo cp /proc/mdstat /etc/mdadm/mdadm.conf puis sudo reboot",
      "sudo mdadm --detail --scan | sudo tee -a /etc/mdadm.conf puis sudo dracut --force",
    ],
    correct: 0,
    explanation: "Sous Ubuntu, la configuration se sauvegarde dans /etc/mdadm/mdadm.conf (avec le sous-repertoire) via --detail --scan, puis update-initramfs -u met a jour le ramdisk de demarrage. Sous Fedora, c'est /etc/mdadm.conf et dracut --force.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Quelle commande permet de simuler la panne d'un disque /dev/sdc dans l'array /dev/md0 ?",
    options: [
      "sudo mdadm --manage /dev/md0 --remove /dev/sdc",
      "sudo mdadm --manage /dev/md0 --fail /dev/sdc",
      "sudo mdadm --manage /dev/md0 --down /dev/sdc",
      "sudo mdadm --manage /dev/md0 --fault /dev/sdc",
    ],
    correct: 1,
    explanation: "La commande '--fail' marque un disque comme defaillant dans l'array. Cela permet de tester la reconstruction vers un spare sans avoir a physiquement debrancher un disque.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Dans quelle situation le disque Spare d'un RAID 5 s'active-t-il automatiquement ?",
    options: [
      "Quand l'array depasse 80% d'utilisation",
      "Quand le systeme redemarrage",
      "Quand un disque actif est marque comme defaillant",
      "Quand la synchronisation initiale est terminee",
    ],
    correct: 2,
    explanation: "Le spare s'active automatiquement quand mdadm detecte qu'un disque actif est marque --fail ou repond plus. La reconstruction commence immediatement sans intervention humaine.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Quelle commande affiche les details complets d'un array RAID /dev/md0, incluant l'etat de chaque disque ?",
    options: [
      "sudo mdadm --status /dev/md0",
      "sudo mdadm --info /dev/md0",
      "sudo mdadm --detail /dev/md0",
      "sudo mdadm --show /dev/md0",
    ],
    correct: 2,
    explanation: "'mdadm --detail /dev/md0' affiche l'etat complet de l'array : niveau RAID, etat (clean/degraded), nombre de disques actifs/spare/faulty, et le role de chaque disque.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Quelle commande permet d'etendre un RAID 5 de 3 a 4 disques actifs ?",
    options: [
      "sudo mdadm --expand /dev/md0 --raid-devices=4",
      "sudo mdadm --grow /dev/md0 --raid-devices=4",
      "sudo mdadm --extend /dev/md0 --devices=4",
      "sudo mdadm --resize /dev/md0 --raid-devices=4",
    ],
    correct: 1,
    explanation: "'mdadm --grow /dev/md0 --raid-devices=4' etend l'array au nouveau nombre de disques actifs. Le disque spare precedemment ajoute devient actif et la reconstruction commence automatiquement.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Comment surveiller la progression de la synchronisation d'un array RAID en temps reel ?",
    options: [
      "sudo mdadm --watch /dev/md0",
      "sudo journalctl -f -u mdmonitor",
      "watch cat /proc/mdstat",
      "sudo mdadm --monitor --scan",
    ],
    correct: 2,
    explanation: "'watch cat /proc/mdstat' rafraichit automatiquement la sortie de /proc/mdstat toutes les 2 secondes, permettant de suivre le pourcentage de synchronisation et la vitesse en temps reel.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Quel fichier systeme expose en temps reel l'etat de tous les arrays RAID sous Linux ?",
    options: [
      "/etc/mdadm/mdadm.conf",
      "/proc/mdstat",
      "/sys/block/md0/md/sync_action",
      "/var/log/mdadm.log",
    ],
    correct: 1,
    explanation: "/proc/mdstat est le fichier virtuel du noyau Linux qui expose l'etat en temps reel de tous les arrays RAID actifs : niveau, etat, disques membres, progression de synchronisation.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Quelle option de mdadm permet de creer un RAID 1 avec un seul disque en attendant le second ?",
    options: [
      "--raid-devices=1 /dev/sdb",
      "--raid-devices=2 /dev/sdb missing",
      "--raid-devices=2 /dev/sdb --pending",
      "--raid-devices=2 /dev/sdb --incomplete",
    ],
    correct: 1,
    explanation: "Le mot-cle 'missing' remplace le disque absent dans la commande de creation. Le RAID est cree en mode degrade avec un seul disque, puis on ajoute le second avec --add.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Quelle est la commande correcte pour arreter l'array /dev/md0 ?",
    options: [
      "sudo mdadm --stop /dev/md0",
      "sudo mdadm --halt /dev/md0",
      "sudo systemctl stop md0",
      "sudo mdadm --down /dev/md0",
    ],
    correct: 0,
    explanation: "'mdadm --stop /dev/md0' arrete l'array proprement. Il faut imperativement demonter le volume (umount) avant d'arreter l'array, sinon des donnees pourraient etre corrompues.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Quelle commande permet de reassembler un array RAID 1 en mode force avec un seul disque survivant ?",
    options: [
      "sudo mdadm --create /dev/md0 /dev/sdc --force",
      "sudo mdadm --assemble --run /dev/md0 /dev/sdc --force",
      "sudo mdadm --rebuild /dev/md0 /dev/sdc --force",
      "sudo mdadm --start /dev/md0 /dev/sdc --force",
    ],
    correct: 1,
    explanation: "'mdadm --assemble --run /dev/md0 /dev/sdc --force' reassemble l'array en mode degrade avec uniquement le disque survivant. Cela permet de recuperer les donnees apres une panne.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Apres avoir etendu un RAID 5 avec mdadm --grow, quelle etape supplementaire est necessaire pour utiliser l'espace gagne ?",
    options: [
      "Redemarrer le serveur",
      "Reformater le volume RAID",
      "Etendre le systeme de fichiers avec resize2fs ou xfs_growfs",
      "Demonter et remonter le volume",
    ],
    correct: 2,
    explanation: "Apres mdadm --grow et la reconstruction, le systeme de fichiers occupe toujours l'ancienne taille. Il faut etendre avec 'resize2fs /dev/md0' pour ext4 ou 'xfs_growfs /point_montage' pour XFS.",
  },
  {
    id: 26,
    type: "qcm",
    question: "Comment accelerer la vitesse de synchronisation maximale d'un array RAID a 100 MB/s ?",
    options: [
      "sudo mdadm --speed /dev/md0 1000000",
      "echo 1000000 > /proc/sys/dev/raid/speed_limit_max",
      "sudo sysctl dev.raid.speed_limit_max=1000000",
      "sudo mdadm --set-speed 1000000 /dev/md0",
    ],
    correct: 1,
    explanation: "La vitesse de synchronisation est controlee via /proc/sys/dev/raid/speed_limit_max. La valeur est en Ko/s, donc 1000000 correspond a 1000 MB/s. Par defaut, la limite est intentionnellement basse pour ne pas impacter les performances.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Quel niveau RAID faut-il utiliser pour combiner performance maximale en lecture/ecriture et redondance ?",
    options: [
      "RAID 0",
      "RAID 1",
      "RAID 5",
      "RAID 10",
    ],
    correct: 3,
    explanation: "Le RAID 10 (RAID 1+0) combine le mirroring (redondance) et le striping (performances). Il offre les meilleures performances en lecture et ecriture avec redondance, mais necessite au minimum 4 disques et utilise 50% de la capacite.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Quelle commande permet de voir a quel array RAID appartient un disque /dev/sdb ?",
    options: [
      "sudo mdadm --detail /dev/sdb",
      "sudo mdadm --query /dev/sdb",
      "sudo mdadm --info /dev/sdb",
      "sudo mdadm --examine /dev/sdb",
    ],
    correct: 1,
    explanation: "'mdadm --query /dev/sdb' indique a quel array appartient le disque. La commande 'mdadm --examine /dev/sdb' affiche quant a elle les metadonnees du superbloc RAID stockees sur le disque.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Quelle est l'etat d'un array RAID 5 affiche 'degraded' dans mdadm --detail ?",
    options: [
      "L'array fonctionne normalement avec tous ses disques",
      "L'array fonctionne mais un disque est manquant ou defaillant",
      "L'array est arrete et ne repond plus",
      "L'array est en cours de creation initiale",
    ],
    correct: 1,
    explanation: "Un etat 'degraded' signifie que l'array fonctionne encore (les donnees sont accessibles) mais qu'un ou plusieurs disques sont absents ou defaillants. La tolerance aux pannes est reduite — il faut remplacer le disque rapidement.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Quelle sequence est correcte pour retirer proprement un disque defaillant /dev/sdc d'un array /dev/md0 ?",
    options: [
      "mdadm --remove /dev/md0 /dev/sdc",
      "mdadm --manage /dev/md0 --fail /dev/sdc puis mdadm --manage /dev/md0 --remove /dev/sdc",
      "mdadm --manage /dev/md0 --remove /dev/sdc puis mdadm --manage /dev/md0 --fail /dev/sdc",
      "mdadm --stop /dev/md0 puis mdadm --manage /dev/md0 --remove /dev/sdc",
    ],
    correct: 1,
    explanation: "Il faut d'abord marquer le disque comme defaillant (--fail) pour le sortir de l'array proprement, puis le retirer (--remove). L'ordre inverse est impossible — on ne peut pas retirer un disque encore considere actif.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Comment creer un RAID 5 avec 3 disques actifs et 1 disque spare en une seule commande ?",
    options: [
      "sudo mdadm --create /dev/md0 -l5 -n3 /dev/sdb /dev/sdc /dev/sdd --spare-devices=1 /dev/sde",
      "sudo mdadm --create /dev/md0 -l5 -n4 /dev/sdb /dev/sdc /dev/sdd --spare /dev/sde",
      "sudo mdadm --create /dev/md0 -l5 -n3 /dev/sdb /dev/sdc /dev/sdd /dev/sde --hot-spare",
      "sudo mdadm --create /dev/md0 -l5 -n3 -s1 /dev/sdb /dev/sdc /dev/sdd /dev/sde",
    ],
    correct: 0,
    explanation: "L'option '--spare-devices=1' specifie le nombre de spares, suivi du peripherique spare. Les options courtes equivalentes sont -l5 (level 5) et -n3 (3 disques actifs). Le spare est liste apres les disques actifs.",
  },
  {
    id: 32,
    type: "qcm",
    question: "Quel systeme de fichiers NE PEUT PAS etre reduit sous Linux ?",
    options: [
      "ext3",
      "ext4",
      "xfs",
      "btrfs",
    ],
    correct: 2,
    explanation: "XFS ne supporte pas la reduction de taille — il peut uniquement etre etendu. ext4 peut etre reduit (avec resize2fs apres e2fsck). C'est une contrainte importante lors du choix du systeme de fichiers sur Fedora/RHEL.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Quelle commande permet de scanner et afficher tous les arrays RAID actifs sur le systeme ?",
    options: [
      "sudo mdadm --list",
      "sudo mdadm --detail --scan",
      "sudo mdadm --show --all",
      "cat /etc/mdadm/mdadm.conf",
    ],
    correct: 1,
    explanation: "'mdadm --detail --scan' scanne le systeme et affiche la configuration de tous les arrays actifs dans un format compatible avec mdadm.conf. C'est la commande utilisee pour generer le fichier de configuration.",
  },
  {
    id: 34,
    type: "qcm",
    question: "Quel est le role de la commande 'update-initramfs -u' apres sauvegarde de mdadm.conf sous Ubuntu ?",
    options: [
      "Redemarrer le service mdmonitor",
      "Recharger la configuration reseau",
      "Mettre a jour le ramdisk de demarrage pour inclure la configuration RAID",
      "Verifier l'integrite des disques RAID",
    ],
    correct: 2,
    explanation: "update-initramfs -u regenere l'image initramfs (ramdisk initial charge au demarrage) pour y inclure la configuration mdadm.conf. Sans cette etape, le RAID peut ne pas etre assemble correctement au boot.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Quelle commande affiche les disques et partitions disponibles avec leurs tailles et types ?",
    options: [
      "lsblk -f",
      "sudo fdisk -l",
      "df -h",
      "sudo pvs",
    ],
    correct: 1,
    explanation: "'sudo fdisk -l' liste tous les disques et partitions du systeme avec leurs tailles, secteurs et types. 'lsblk' affiche une vue arborescente mais sans les details de partitionnement.",
  },
  {
    id: 36,
    type: "qcm",
    question: "Dans un RAID 5 a 3 disques, combien de disques peuvent tomber en panne avant la perte de donnees ?",
    options: [
      "0 disque",
      "1 disque",
      "2 disques",
      "3 disques",
    ],
    correct: 1,
    explanation: "Le RAID 5 tolere la panne d'exactement 1 disque grace a la parite repartie. Si un second disque tombe en panne pendant la reconstruction, toutes les donnees sont perdues — d'ou l'importance d'un disque spare.",
  },
  {
    id: 37,
    type: "qcm",
    question: "Quelle est la difference entre 'mdadm --stop' et 'mdadm --remove' ?",
    options: [
      "--stop arrete l'array, --remove retire un disque de l'array",
      "--stop efface l'array, --remove l'arrete temporairement",
      "--stop retire un disque, --remove arrete l'array",
      "Ces deux commandes font la meme chose",
    ],
    correct: 0,
    explanation: "'mdadm --stop /dev/md0' arrete l'ensemble de l'array RAID. 'mdadm --manage /dev/md0 --remove /dev/sdb' retire un disque specifique de l'array. Ce sont deux operations completement differentes.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Quelle commande faut-il utiliser pour etendre le systeme de fichiers XFS apres agrandissement d'un RAID sur Fedora ?",
    options: [
      "sudo resize2fs /dev/md0",
      "sudo xfs_repair /dev/md0",
      "sudo xfs_growfs /mnt/raid",
      "sudo xfs_admin -e /dev/md0",
    ],
    correct: 2,
    explanation: "'xfs_growfs /mnt/raid' etend le systeme de fichiers XFS en utilisant le point de montage (pas le peripherique). Contrairement a resize2fs, xfs_growfs prend le point de montage et non le peripherique comme argument.",
  },
  {
    id: 39,
    type: "qcm",
    question: "Quel est le nom de l'outil standard Linux pour gerer le RAID logiciel ?",
    options: [
      "raidtools",
      "mdadm",
      "lvm2",
      "dmsetup",
    ],
    correct: 1,
    explanation: "mdadm (Multiple Device ADMinistrator) est l'outil standard de reference sous Linux pour creer, gerer et surveiller les arrays RAID logiciel. Il remplace l'ancien outil raidtools.",
  },
  {
    id: 40,
    type: "qcm",
    question: "Quel est l'avantage principal de combiner LVM par-dessus un RAID 5 ?",
    options: [
      "Ameliorer les performances d'ecriture du RAID",
      "Beneficier a la fois de la redondance RAID et de la flexibilite LVM",
      "Reduire le nombre de disques necessaires",
      "Simplifier la configuration mdadm",
    ],
    correct: 1,
    explanation: "La combinaison RAID + LVM apporte le meilleur des deux mondes : le RAID assure la redondance et la protection contre les pannes disque, tandis que LVM permet de creer et redimensionner des volumes logiques flexibles sans complexite supplementaire.",
  },
];

export default function QuizzRaid() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — RAID Logiciel avec mdadm"
      courseLink="/idosr/linux/lesson-06"
    />
  );
}