import React from "react";
import QuizEngine from "@site/src/components/QuizEngine";

const questions = [
  // ── Vrai / Faux ──────────────────────────────────────────────────────────
  {
    id: 1,
    type: "vf",
    question: "DNS signifie Domain Name System et traduit les noms de domaine en adresses IP ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. DNS (Domain Name System) traduit les noms de domaine en adresses IP et vice-versa.",
  },
  {
    id: 2,
    type: "vf",
    question: "Une zone DNS de type `slave` possede une base de donnees en lecture et ecriture ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Le type `slave` est en lecture seule ; c'est le type `master` qui permet la lecture et l'ecriture.",
  },
  {
    id: 3,
    type: "vf",
    question: "L'enregistrement SOA est le premier enregistrement obligatoire de tout fichier de zone DNS ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. L'enregistrement SOA (Start of Authority) est toujours le premier enregistrement d'une zone DNS.",
  },
  {
    id: 4,
    type: "vf",
    question: "Un enregistrement CNAME associe directement un nom d'hote a une adresse IPv4 ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Un enregistrement CNAME est un alias qui pointe vers un autre nom d'hote. C'est l'enregistrement A qui associe un nom a une adresse IPv4.",
  },
  {
    id: 5,
    type: "vf",
    question: "L'enregistrement PTR se trouve dans la zone inverse et resout une adresse IP en nom d'hote ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. L'enregistrement PTR est utilise dans la zone inverse pour resoudre une adresse IP en nom d'hote.",
  },
  {
    id: 6,
    type: "vf",
    question: "Dans un enregistrement MX, un nombre de priorite plus eleve signifie que le serveur est plus prioritaire ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Dans un enregistrement MX, plus le nombre est petit, plus le serveur est prioritaire.",
  },
  {
    id: 7,
    type: "vf",
    question: "La commande `named-checkzone` permet de verifier la syntaxe d'un fichier de zone DNS ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. `named-checkzone nom_zone fichier` verifie la syntaxe d'un fichier de zone sans demarrer le service.",
  },
  {
    id: 8,
    type: "vf",
    question: "Dans un fichier de zone, un nom termine sans point final est considere comme un nom absolu par BIND ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Sans point final, BIND ajoute automatiquement le nom de domaine de la zone, ce qui peut produire des erreurs comme `mail.ofppt.local.ofppt.local`.",
  },
  {
    id: 9,
    type: "vf",
    question: "Le DDNS permet au serveur DHCP de mettre a jour automatiquement les enregistrements DNS lors de l'attribution d'une adresse IP ?",
    options: ["Vrai", "Faux"],
    correct: 0,
    explanation: "VRAI. Le DDNS (DNS Dynamique) synchronise les enregistrements DNS avec les attributions DHCP en temps reel.",
  },
  {
    id: 10,
    type: "vf",
    question: "Sur Ubuntu/Debian, le service DNS BIND9 s'appelle `named` dans les commandes systemctl ?",
    options: ["Vrai", "Faux"],
    correct: 1,
    explanation: "FAUX. Sur Ubuntu/Debian, le service s'appelle `bind9` (`systemctl restart bind9`). C'est sur Fedora/Red Hat qu'il s'appelle `named`.",
  },

  // ── QCM ──────────────────────────────────────────────────────────────────
  {
    id: 11,
    type: "qcm",
    question: "Quel type de zone DNS contient la base de donnees originale en lecture et ecriture ?",
    options: ["slave", "hint", "master", "forward"],
    correct: 2,
    explanation: "Le type `master` est le serveur DNS principal avec une base de donnees en lecture et ecriture.",
  },
  {
    id: 12,
    type: "qcm",
    question: "Quel enregistrement DNS est utilise pour definir un alias pointant vers un autre nom d'hote ?",
    options: ["A", "PTR", "MX", "CNAME"],
    correct: 3,
    explanation: "L'enregistrement CNAME (Canonical Name) donne un surnom a un nom d'hote existant.",
  },
  {
    id: 13,
    type: "qcm",
    question: "Quel fichier contient la declaration des zones DNS sur Ubuntu/Debian ?",
    options: ["/etc/bind/named.conf", "/etc/bind/named.conf.options", "/etc/bind/named.conf.local", "/var/cache/bind/named.conf"],
    correct: 2,
    explanation: "Sur Ubuntu/Debian, les zones sont declarees dans `/etc/bind/named.conf.local`.",
  },
  {
    id: 14,
    type: "qcm",
    question: "Quelle option DNS dans `named.conf.options` permet de definir des serveurs DNS externes de secours ?",
    options: ["allow-query", "recursion", "forwarders", "listen-on"],
    correct: 2,
    explanation: "L'option `forwarders` definit les serveurs DNS externes utilises quand la reponse n'est pas locale.",
  },
  {
    id: 15,
    type: "qcm",
    question: "Que represente le symbole `@` dans un fichier de zone DNS ?",
    options: ["L'adresse du serveur DHCP", "Le nom de domaine principal de la zone", "Le serveur de messagerie", "L'adresse IP du serveur"],
    correct: 1,
    explanation: "`@` represente le nom de domaine principal de la zone, par exemple `ofppt.local`.",
  },
  {
    id: 16,
    type: "qcm",
    question: "Quel parametre du SOA indique le numero de version de la zone pour la synchronisation avec les serveurs secondaires ?",
    options: ["Refresh", "Retry", "Serial", "Expire"],
    correct: 2,
    explanation: "Le parametre `Serial` est le numero de version de la zone. Les serveurs secondaires l'utilisent pour savoir si la zone a change.",
  },
  {
    id: 17,
    type: "qcm",
    question: "Quelle commande permet de tester la resolution DNS directe sur le serveur local ?",
    options: ["ping 127.0.0.1", "dig @127.0.0.1 www.ofppt.local", "nmap 127.0.0.1", "curl 127.0.0.1"],
    correct: 1,
    explanation: "`dig @127.0.0.1 www.ofppt.local` interroge le serveur DNS local pour resoudre un nom en adresse IP.",
  },
  {
    id: 18,
    type: "qcm",
    question: "Quel fichier de zone est edite pour configurer la resolution inverse (IP vers nom) ?",
    options: ["db.ofppt.local", "db.192.168.10", "named.conf.local", "named.conf.options"],
    correct: 1,
    explanation: "Le fichier de zone inverse (ex: `db.192.168.10`) contient les enregistrements PTR pour la resolution IP vers nom.",
  },
  {
    id: 19,
    type: "qcm",
    question: "Sur Fedora/Red Hat, quel fichier regroupe a la fois les options globales et la declaration des zones DNS ?",
    options: ["/etc/bind/named.conf.local", "/etc/named.conf", "/var/named/named.conf", "/etc/bind/named.conf"],
    correct: 1,
    explanation: "Sur Fedora/Red Hat, `/etc/named.conf` regroupe les options globales et les declarations de zones dans un seul fichier.",
  },
  {
    id: 20,
    type: "qcm",
    question: "Quelle directive dans la declaration de zone autorise un serveur DHCP a mettre a jour dynamiquement les enregistrements DNS ?",
    options: ["allow-transfer", "notify yes", "allow-update", "type slave"],
    correct: 2,
    explanation: "`allow-update` autorise l'adresse IP indiquee (ex: serveur DHCP) a modifier les enregistrements de la zone dynamiquement.",
  },
  {
    id: 21,
    type: "qcm",
    question: "Quel type de zone DNS ne copie que les enregistrements NS et SOA pour localiser les serveurs autoritaires ?",
    options: ["slave", "forward", "stub", "hint"],
    correct: 2,
    explanation: "Le type `stub` ne contient que NS + SOA pour localiser les serveurs autoritaires de la zone.",
  },
  {
    id: 22,
    type: "qcm",
    question: "Quelle commande verifie la syntaxe du fichier principal `named.conf` sans demarrer le service ?",
    options: ["named-checkzone", "named-checkconf", "bind9 --check", "dig -t AXFR"],
    correct: 1,
    explanation: "`named-checkconf` verifie la syntaxe du fichier `named.conf` et retourne les erreurs de configuration.",
  },
  {
    id: 23,
    type: "qcm",
    question: "Que signifie $TTL dans un fichier de zone DNS ?",
    options: [
      "Le temps maximum que le serveur attend une reponse",
      "La duree pendant laquelle une reponse peut etre mise en cache par d'autres serveurs",
      "Le delai avant que le slave verifie les mises a jour",
      "La priorite du serveur de messagerie"
    ],
    correct: 1,
    explanation: "$TTL (Time To Live) definit la duree pendant laquelle une reponse DNS peut etre mise en cache par d'autres serveurs ou clients.",
  },
  {
    id: 24,
    type: "qcm",
    question: "Pourquoi est-il necessaire d'ajouter un enregistrement A apres un enregistrement NS ?",
    options: [
      "Pour des raisons de securite DNSSEC",
      "Pour que les autres serveurs DNS connaissent l'adresse IP du serveur autoritaire",
      "Pour activer la recursion",
      "Pour autoriser les transferts de zone"
    ],
    correct: 1,
    explanation: "Le NS indique quel serveur est autoritaire, mais sans l'enregistrement A associe, les autres DNS ne peuvent pas connaitre son adresse IP pour l'interroger.",
  },
  {
    id: 25,
    type: "qcm",
    question: "Quel outil de ligne de commande est recommande pour diagnostiquer les requetes DNS ?",
    options: ["nslookup", "ping", "dig", "traceroute"],
    correct: 2,
    explanation: "`dig` est l'outil de diagnostic DNS recommande. Il permet la resolution directe, inverse et l'interrogation par type d'enregistrement.",
  },
  {
    id: 26,
    type: "qcm",
    question: "Quelle option dans `dhcpd.conf` active la mise a jour dynamique du DNS depuis le serveur DHCP ?",
    options: ["ddns-update-style", "ddns-updates on", "ignore client-updates", "ddns-domainname"],
    correct: 1,
    explanation: "`ddns-updates on` active la mise a jour dynamique du DNS. `ddns-update-style` definit le style, mais c'est `ddns-updates on` qui active la fonctionnalite.",
  },
  {
    id: 27,
    type: "qcm",
    question: "Quelle commande `rndc` permet de geler une zone pour arreter temporairement les mises a jour dynamiques ?",
    options: ["rndc reload", "rndc flush", "rndc freeze", "rndc stop"],
    correct: 2,
    explanation: "`rndc freeze nom_zone` gele la zone et arrete les mises a jour dynamiques. `rndc thaw` la degele ensuite.",
  },
  {
    id: 28,
    type: "qcm",
    question: "Sur Ubuntu/Debian, ou sont stockes par defaut les fichiers de zones BIND ?",
    options: ["/var/named/", "/etc/named/", "/etc/bind/ ou /var/cache/bind/", "/usr/share/bind9/"],
    correct: 2,
    explanation: "Sur Ubuntu/Debian, les fichiers de zones sont places dans `/etc/bind/` ou `/var/cache/bind/` selon la configuration.",
  },
  {
    id: 29,
    type: "qcm",
    question: "Quel enregistrement DNS permet de definir le serveur de messagerie d'un domaine ?",
    options: ["A", "NS", "MX", "TXT"],
    correct: 2,
    explanation: "L'enregistrement MX (Mail Exchanger) specifie le serveur de messagerie du domaine avec un niveau de priorite.",
  },
  {
    id: 30,
    type: "qcm",
    question: "Quel parametre SOA definit la duree maximale pendant laquelle un serveur slave conserve la zone sans pouvoir contacter le master ?",
    options: ["Refresh", "Retry", "Minimum TTL", "Expire"],
    correct: 3,
    explanation: "`Expire` definit la duree maximale pendant laquelle le slave garde la zone valide si le master est inaccessible.",
  },
  {
    id: 31,
    type: "qcm",
    question: "Quelle commande permet de tester la resolution DNS inverse sur le serveur local ?",
    options: ["dig @127.0.0.1 ofppt.local PTR", "dig @127.0.0.1 -x 192.168.10.2", "nslookup 192.168.10.2", "host -t PTR 192.168.10.2"],
    correct: 1,
    explanation: "`dig @127.0.0.1 -x 192.168.10.2` effectue une resolution inverse en interrogeant le serveur DNS local.",
  },
  {
    id: 32,
    type: "qcm",
    question: "Quelle directive dans `named.conf.options` definit les interfaces reseau sur lesquelles BIND ecoute ?",
    options: ["allow-query", "forwarders", "listen-on", "directory"],
    correct: 2,
    explanation: "`listen-on` definit les interfaces reseau sur lesquelles le serveur DNS accepte les requetes.",
  },
  {
    id: 33,
    type: "qcm",
    question: "Dans la configuration DDNS sans cle TSIG, quelle valeur est attribuee a `allow-update` pour autoriser toutes les mises a jour ?",
    options: ["allow-update { localhost; }", "allow-update { any; }", "allow-update { none; }", "allow-update { 127.0.0.1; }"],
    correct: 1,
    explanation: "`allow-update { any; }` autorise n'importe quelle source a mettre a jour la zone dynamiquement (configuration simple, non securisee).",
  },
  {
    id: 34,
    type: "qcm",
    question: "Sur Fedora/Red Hat, quelle commande SELinux autorise BIND a ecrire dans les zones ?",
    options: ["semanage port -a -t dns_port_t -p tcp 53", "setsebool -P named_write_master_zones on", "restorecon -r /var/named/", "chcon -t named_zone_t /var/named/"],
    correct: 1,
    explanation: "`setsebool -P named_write_master_zones on` est la commande SELinux requise pour autoriser BIND a ecrire dans les fichiers de zones sur Fedora/Red Hat.",
  },
  {
    id: 35,
    type: "qcm",
    question: "Quelle est la difference principale entre une zone `forward` et une zone `slave` ?",
    options: [
      "La zone forward copie les enregistrements, la zone slave redirige les requetes",
      "La zone slave copie les enregistrements depuis le master, la zone forward redirige les requetes vers d'autres DNS",
      "Les deux sont identiques mais avec des fichiers differents",
      "La zone forward est plus securisee que la zone slave"
    ],
    correct: 1,
    explanation: "Une zone `slave` copie la zone complete depuis le master. Une zone `forward` redirige simplement les requetes vers d'autres serveurs DNS sans stocker de donnees.",
  },
  {
    id: 36,
    type: "qcm",
    question: "Quelle option dans `dhcpd.conf` indique que c'est le serveur DHCP qui gere les mises a jour DNS, et non le client ?",
    options: ["ddns-updates on", "ddns-update-style interim", "ignore client-updates", "ddns-domainname"],
    correct: 2,
    explanation: "`ignore client-updates` indique au serveur DHCP de gerer lui-meme les mises a jour DNS et d'ignorer les demandes des clients.",
  },
  {
    id: 37,
    type: "qcm",
    question: "Quel algorithme est utilise par la commande `tsig-keygen` pour generer une cle TSIG securisee ?",
    options: ["RSA-2048", "HMAC-SHA256", "AES-128", "MD5"],
    correct: 1,
    explanation: "`tsig-keygen -a HMAC-SHA256 dhcp-key` genere une cle TSIG avec l'algorithme HMAC-SHA256 pour securiser les echanges DDNS.",
  },
  {
    id: 38,
    type: "qcm",
    question: "Quel fichier de configuration DNS sur Ubuntu/Debian contient les options globales comme `recursion`, `forwarders` et `listen-on` ?",
    options: ["/etc/bind/named.conf", "/etc/bind/named.conf.local", "/etc/bind/named.conf.options", "/etc/resolv.conf"],
    correct: 2,
    explanation: "Sur Ubuntu/Debian, `/etc/bind/named.conf.options` contient les parametres globaux du serveur DNS comme la recursion, les forwarders et les interfaces d'ecoute.",
  },
  {
    id: 39,
    type: "qcm",
    question: "Quel port doit etre ouvert dans le pare-feu pour permettre les requetes DNS ?",
    options: ["Port 80 TCP/UDP", "Port 443 TCP/UDP", "Port 53 TCP/UDP", "Port 22 TCP"],
    correct: 2,
    explanation: "Le port 53 en TCP et UDP est le port standard du protocole DNS. Il doit etre autorise dans le pare-feu pour que le serveur DNS soit accessible.",
  },
  {
    id: 40,
    type: "qcm",
    question: "Que fait la directive `notify yes` dans la declaration d'une zone DNS ?",
    options: [
      "Envoie un email a l'administrateur en cas d'erreur",
      "Notifie automatiquement les serveurs secondaires quand la zone est modifiee",
      "Active les notifications systeme dans syslog",
      "Informe les clients DNS des changements d'adresse"
    ],
    correct: 1,
    explanation: "`notify yes` demande au serveur master d'envoyer automatiquement un message NOTIFY aux serveurs secondaires (slaves) quand la zone est modifiee.",
  },
];

export default function QuizzDNS() {
  return (
    <QuizEngine
      questions={questions}
      title="Quiz — Serveur DNS et DDNS"
      courseLink="/docs/linux/lesson-03"
    />
  );
}